### PR TITLE
feat: added setting to always play videos in fullscreen

### PR DESCRIPTION
**Pull request by saideepesh000**
---
feat: added setting to always play videos in fullscreen
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
#647 

**Description**
Now users can set the default mode to watch videos in fullscreen mode. This setting will be available on Player Settings. 

**Screenshots (if appropriate)**
fullscreen

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version:10
 - FreeTube version: Latest

**Additional context**

### CODE REVIEW

**Comment by saideepesh000** [comment]
Damn U linting :(

**Comment by PrestonN** [comment]
I likely won't be able to properly test this today as I'm trying to focus on a fix for some outstanding issues at the moment.

The one thing I do notice is please make sure this works when you navigate to a video from the video page. Navigation works slightly differently for pages that uses the same view so that will also need to be tested. If it already works with that then there's nothing to worry about.

**Comment by saideepesh000** [comment]
@PrestonN, I tried every possible way of watching the video(Eg: through searching, through the trending page, through saved videos, through subscriptions, etc), it seems like working fine, do check from your side too.

**Comment by saideepesh000** [comment]
Hey @PrestonN, sorry for rushing this a bit, I'm afraid that this may end up like [this](https://github.com/gkoberger/stacksort/pull/4#issuecomment-15081351), lol

**Comment by PrestonN** [comment]
Hey there, apologies for taking so long to look into this. I was finally able to do some testing and here's what I found.

- Having FreeTube autoplay a video (either via "Play Next Video" / "Autoplay or by watching a playlist) doesn't set the video to full screen unless the user clicks on the window again while the next video is loading. Please take a look into this and if you have any troubles I'll see what sort of solution can be made.
- Switching between Legacy / Dash / Audio formats forces full screen when the toggle is enabled. Let's not have the video full screen in this case even when the setting is enabled.

This one is a nice to have but I won't require it for this PR.
- Let's close out of full screen when a video ends so that the user can see the notification that the next video is about to play. Doing this may even help with having the full screen come back on when the next video plays.

The code structure itself looks fine. Please fix the above problems and we'll be good to merge.

**Review by PrestonN — CHANGES_REQUESTED** [review]
Hey there, apologies for taking so long to look into this. I was finally able to do some testing and here's what I found.

- Having FreeTube autoplay a video (either via "Play Next Video" / "Autoplay or by watching a playlist) doesn't set the video to full screen unless the user clicks on the window again while the next video is loading. Please take a look into this and if you have any troubles I'll see what sort of solution can be made.
- Switching between Legacy / Dash / Audio formats forces full screen when the toggle is enabled. Let's not have the video full screen in this case even when the setting is enabled.

This one is a nice to have but I won't require it for this PR.
- Let's close out of full screen when a video ends so that the user can see the notification that the next video is about to play. Doing this may even help with having the full screen come back on when the next video plays.

The code structure itself looks fine. Please fix the above problems and we'll be good to merge.

**Comment by saideepesh000** [comment]
Okay, I'll update it soon

**Comment by saideepesh000** [comment]
Hey @PrestonN, I could able to solve this(somewhat), now this `Enable fullscreen by default setting` only works when the video starts playing, so in order to understand this I added a `tooltip` for the setting, please make necessary changes to `tooltip` text to make it as intuitive as possible.

**Comment by saideepesh000** [comment]
> 
>     * Switching between Legacy / Dash / Audio formats forces full screen when the toggle is enabled. Let's not have the video full screen in this case even when the setting is enabled.

I'm not sure I understood this.

**Comment by PrestonN** [comment]
When you're watching a video, there is a button in between the download and share button that allows you to swap between the DASH / Legacy / Audio formats. When this button is pressed, it initializes the player again and will force the player to be full screen if the setting is enabled. I would like it so that the player does not enable full screen when these buttons are used even if the setting is enabled.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @saideepesh000 would it be possible for u to implement the same functionality for 'Fullwindow'? That would be really nice.

**Comment by peepopoggers** [comment]
Please resolve conflicts and update us otherwise close this request. @saideepesh000

**Comment by jasonhenriquez** [comment]
> Please resolve conflicts and update us otherwise close this request. @saideepesh000

I am bumping this comment. We understand that it is a busy time, so you may not have the time to work on this any further. However, given that this is an in-demand issue, please respond before the end of the week or we will have to re-assign the issue and close this PR.

**Comment by ChunkyProgrammer** [comment]
I didn't actually test this code but from what I understand by looking at it, it looks like both defaultFullScreenMode and defaultTheatreMode can be enabled at the same time which I don't think should be the case. So another change might be needed to unset theatremode when full screen is made default and to unset fullscreen when theatre is made default.

**Comment by jasonhenriquez** [comment]
> I didn't actually test this code but from what I understand by looking at it, it looks like both defaultFullScreenMode and defaultTheatreMode can be enabled at the same time which I don't think should be the case.

Why can't this be the case? I think you're wrong on this one.

**Comment by ChunkyProgrammer** [comment]
> Why can't this be the case? I think you're wrong on this one.

Wouldn't one of the settings just end up overriding the other?  (Fullscreen over theatre mode)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Quick side note: I'm not sure if i interpreted the discussion correctly 

I agree with @ChunkyProgrammer i think its better  to do the following

If the toggle Enable theater mode by default is enabled

And u try to

Enable fullscreen by default by clicking on the toggle

The toggle of theater mode must turn off.

This must also happen when fullscreen by default is enabled and u want to turn on theater mode by default.

With this u wont get in any weird situation where we must make choices what default has the highest priority to override when multiple toggles are enabled.

**Comment by jasonhenriquez** [comment]
> Wouldn't one of the settings just end up overriding the other? (Fullscreen over theatre mode)

Full screen would definitely be the dominant feature, but when full screen is exited, theater mode would be active by default. Similarly, since these settings are overridden by their last state when watching a set of videos, all videos switched into in the session after exiting full screen would automatically open in theater mode.

**Comment by ChunkyProgrammer** [comment]
Good point! I guess this change would need to be kept in mind for default
fullwindow mode and default theatre mode

**Pull request closed without merging**
