### PR TITLE
Feat: Channel Member Icons + Load Custom Channel Emojis in Comments

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Feat: Channel Member Icons + Load Custom Channel Emojis in Comments
---

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
None

**Description**
This PR will show a visual indicator for channel members & load custom channel emojis

**Screenshots (if appropriate)**
Please add before and after screenshots if there is a visible change.

Channel member icon:
image

Custom channel emoji:
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes, I found comments that were by members or contained custom emojis and they loaded. I also tested to make sure that these changes wouldn't break invidious.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: latest nightly

**Additional context**
This PR requires FreeTubeApp/yt-comment-scraper#32 to be merged & a new version of yt-comment-scraper to be released in order to work

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
For testing, I found this vid to be pretty good. https://youtu.be/3fQSmvT7LOU Pinned comment has a channel icon in it. And there's a channel that is a member that should load on the first page

**Comment by PikachuEXE** [comment]
Custom channel emoji tested but can't find any channel member
image
image

**Review by PikachuEXE — APPROVED** [review]
OK then Channel member icon works too
I thought that's part of his username

**Comment by PikachuEXE** [comment]
Not enough reviewers oops!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its working for me but i dont know why but i see allot of missing profiles pictures.

Capture

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
I am unable to reproduce but this can be setting related issue
Maybe try to inspect the thumbnail URLs?
Here's mine

image

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
LGTM, i had update my dependencies and all the weird issues i got were resolved. Ty for helping out!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe could be the third reviewer @PrestonN ?

**Review by PrestonN — APPROVED** [review]
LGTM

**Pull request merged**
