### PR TITLE
Added Catppuccin Mocha Theme

### PR DESCRIPTION
**Pull request by Rekit0**
---
Added Catppuccin Mocha Theme
---

**Important note**
We may remove your pull request if you do not use this provided PR template correctly.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
Closes: #2394

**Description**
This PR adds Catppuccin Mocha theme based on [Catppuccin Mocha color palette](https://github.com/catppuccin/catppuccin#-palettes) by making the following changes:
- Adds light and dark versions of the logo using Catppuccin Mocha Colors to `/FreeTube/_icons`.
- Adds new window background color using Catppuccin Mocha base color to `/FreeTube/src/main/index.js`.
- Adds the base theme and Catppuccin Mocha accent colors to `/FreeTube/src/renderer/themes.css`.
- Adds `.CatppuccinMocha` class to `/FreeTube/src/renderer/components/ft-share-button/ft-share-button.sass`.
- Adds `'catppuccinMocha'` base theme value to `/FreeTube/src/renderer/components/theme-settings/theme-settings.js`.
- Adds Catppuccin Mocha accent colors names and colors in hex to `/FreeTube/src/renderer/store/modules/utils.js`.
- Adds theme and accent colors name strings to `/FreeTube/static/locales/en-US.yaml`.

**Screenshots (if appropriate)**
Screenshot_2022-07-12_03-32-16
Screenshot_2022-07-12_01-59-01
Screenshot_2022-07-12_01-59-44
Screenshot_2022-07-12_02-01-06
Screenshot_2022-07-12_01-58-10

**Testing (for code that is not small enough to be easily understandable)**
Manually tested:
- Selecting the new theme and observing the changes.
- Selecting each new color as the main theme color and observing the changes.
- Selecting each new color as the secondary color and observing  the changes.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - OS Version: 20.3 (Una)
 - FreeTube version: upstream/development

**Additional context**

### CODE REVIEW

**Review by GilgusMaximus — APPROVED** [review]
Looks good to me. The theme is consistent across pages, the different colors look good.

Nothing is out of the expected and no unnecessary file is changed.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
Everything looks good to me! Only noticed that the text gets cut off but i dont know if we really want to address this.

https://user-images.githubusercontent.com/73130443/179349136-82dc1789-d8f2-4ef0-b898-ca394e96b2b0.mp4

**Comment by Rekit0** [comment]
> Everything looks good to me! Only noticed that the text gets cut off but i dont know if we really want to address this.
> VirtualBoxVM_jTjrHjK6kb.mp4

How about this:
Screenshot_2022-07-16_13-56-19

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
lgtm!

**Review by GilgusMaximus — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]
Tested a few theme colors and a few screens
Might even looks better than what I am using now oops

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Rekit0 how did u create those icons and how did u know what color to give them?

Asking for https://github.com/FreeTubeApp/FreeTube/issues/3915

**Comment by dotunwrap** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I'm assuming they used the base (for dark) and text (for light) colors as defined by the official Mocha theme on [this repo](https://github.com/catppuccin/catppuccin#-palette).

I can easily replicate using the base and text colors for frappe and exporting from GIMP.

**Comment by Rekit0** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I did exactly what @dotunwrap said, I used gimp to change the colors according to Mocha official repo.

**Pull request merged**
