### PR TITLE
Add: Sort Playlist Videos by Length / Duration fixed Issue#5268

### PR DESCRIPTION
**Pull request by creotove**
# Title

## Pull Request Type

- [ ] Bugfix
- [x] Feature Implementation
- [ ] Documentation
- [ ] Other

## Desktop

- **OS:**
- **OS Version:**
- **FreeTube version:**

### CODE REVIEW

**Comment by absidue** [comment]
As I mentioned on that issue, you will have to handle that the duration can be completely missing.

**Comment by creotove** [comment]
@absidue ohh sorry, there is no way that we can sort them properly, but still we can sort them by optionally checking the property and if the there is no property of lengthSeconds then that video will be shown to the top/bottom of the playlist, should I apply this? If any other proposal you need to add to implement in this feature you can add that.

**Comment by absidue** [comment]
If you still want to proceed with this pull request, it definitely needs some handling for videos without durations.

Here are my two suggestions, feel free to pick one or suggest alternative ideas:
1. Hide the sort by duration option when at least one video in the playlist is missing it's duration.
2. Your suggestion of placing videos without duration at the top or bottom of the list depending on the sort direction, with the addition of a message warning the user that the sorting is inaccurate due to one or more videos in the playlist missing their duration.

**Comment by creotove** [comment]
@absidue okk sure i can do that and as i read your alternative consideration in the main issue that user need to manually click the "up" button several times on each video to sort videos according to user need, we can implement a drag and drop feature there instead of manual buttons.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> we can implement a drag and drop feature there instead of manual buttons.

I think that is out of scope of this PR though but if you want to look at it, see https://github.com/FreeTubeApp/FreeTube/issues/4872

**Pull request closed without merging**
