### PR TITLE
Update electron-builder version to ^23.0.2

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
N/A

**Description**
Fixes build task on MacOS 12.3+
Reported in https://github.com/electron-userland/electron-builder/issues/6726

**Screenshots (if appropriate)**
Error message before update
image

**Testing (for code that is not small enough to be easily understandable)**
- Update to MacOS 12.4
- `yarn run build`

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 12.4
 - FreeTube version: e861e70b3374b10430a3f657b626c7f14fc22bea

**Additional context**

### CODE REVIEW

**Review by absidue — APPROVED** [review]
Build still works properly on Windows after the update.

**Comment by PikachuEXE** [comment]
If you want to look for breaking changes in 23.x:
- https://github.com/electron-userland/electron-builder/blob/v23.1.0/CHANGELOG.md#-2022-01-28
- Can't find more yet

But the changelog format looks so strange

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
mirror mirror on the wall who is the chunkiest of them all? @ChunkyProgrammer

**Comment by PikachuEXE** [comment]
Chunkiest 👀

**Review by ChunkyProgrammer — APPROVED** [review]

**Pull request merged**
