### PR TITLE
Fixed tooltip position

### PR DESCRIPTION
**Pull request by saideepesh000**
---
Fixed the improper position of a few Tooltip components on the Settings page
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
#794 

**Description**
This fixes theimproper position of Tooptip on the Settings page with some added extra styles and positions.

**Screenshots (if appropriate)**
Screenshot (285)
Screenshot (284)

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: latest

**Additional context**

### CODE REVIEW

**Comment by PrestonN** [comment]
Please fix your linter issue and then we'll be good to merge

**Review by PrestonN — CHANGES_REQUESTED** [review]
There are a couple of things that I noticed with this PR that I'd like to see fixed.

First off, the new position of the tooltip needs to be added to the validator within `ft-tooltip`. The console currently errors out because it fails this check.

Secondly, the new position type doesn't include the same 'dropdown' animation that the rest of the positions have. Please add the appropriate changes to the tooltip CSS to give this the correct animation.

Lastly, let's change the left value of the new position to `-100px`

Once these are done, then I will be good with merging.

**Comment by saideepesh000** [comment]
> 
> 
> There are a couple of things that I noticed with this PR that I'd like to see fixed.
> 
> First off, the new position of the tooltip needs to be added to the validator within `ft-tooltip`. The console currently errors out because it fails this check.
> 
> Secondly, the new position type doesn't include the same 'dropdown' animation that the rest of the positions have. Please add the appropriate changes to the tooltip CSS to give this the correct animation.
> 
> Lastly, let's change the left value of the new position to `-100px`
> 
> Once these are done, then I will be good with merging.

Okay, I'll do the changes

**Comment by saideepesh000** [comment]
@PrestonN, anything else I need to do 🤔

**Review by PrestonN — APPROVED** [review]
Apologies for the delay on this. Everything looks good to me now. Thank you!

**Pull request merged**
