### PR TITLE
Choose best quality thumbnail for Invidious comment author

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
# Choose best quality thumbnail for Invidious comment author

## Pull Request Type
- [x] Future Bugfix

## Related issue
with https://github.com/iv-org/invidious/pull/4576 there is usually one channel avatar returned so this PR will fix potential issues with loading comments from Invidious. (I ran Invidious locally and was able to get comments to load from that IV PR)

## Testing
- use invidious as primary api
- go to a video
- load comments
- comments load properly (without this PR there will be an error)

## Desktop
- **OS:** Linux Mint
- **OS Version:** 21.3
- **FreeTube version:** 0.20.0

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Convert to draft until it's merged?
Or it can be tested now?

**Comment by ChunkyProgrammer** [comment]
> Convert to draft until it's merged? Or it can be tested now?

Hmm, good point. I was able to get the old format to show up on Invidious a couple of days ago but it seems to be very rare. I'll convert it to draft now

**Comment by absidue** [comment]
You could just sort the array by size (afaik the Invidious API passes through the width and height from YouTube) and then pick one, that way it would support both comment renderers and comment view models.

**Comment by ChunkyProgrammer** [comment]
> You could just sort the array by size (afaik the Invidious API passes through the width and height from YouTube) and then pick one, that way it would support both comment renderers and comment view models.

The `.at(-1)` supports both formats as well (and no need to sort the array)

**Review by absidue — APPROVED** [review]

**Review by jasonhenriquez — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
