### PR TITLE
Feat: Invidious instance autofill

### LINKED ISSUE #1776: Invidious instance suggestion/autofill
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In the general settings u'll find the Current Invidious Instance setting. If u just write in it because the list is too long or u cant find the instance somehow, nothing happens.

**Describe the solution you'd like to see implemented**
I would like to see this changed. If u type something that looks like lets say kavin then it needs to show u the instances that are related to kavin. Its the same behavior the search suggestions work.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
Also the when u hover over the tooltip it says "The Invidious instance that FreeTube will connect to for API calls. Clear the current instance to see a list of public instances to choose from." but when u clear the area it doesnt show u the list of instances. It shows u the list when u start typing. So this is incorrect.

I would also opt of just removing the list because if it gets too long like it is already, u'll need to scroll through it, it uses arguably allot of screen real estate and. What if there will be 100 instances in the future? It is just very bad UX in my opinion. So in my opinion this issue is more of a QoL feature.

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Invidious instance autofill
---

**Important note**
We may remove your pull request if you do not use this provided PR template correctly.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
Closes #1776

**Description**
This PR will filter the invidious instance list when you start typing

**Screenshots (if appropriate)**
image

image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Type in box, navigate with arrows and click enter, click on item

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.15.0 Beta

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Something weird is going on here. When i type https:// the second / disappear.

> I would also opt of just removing the list because if it gets too long like it is already, u'll need to scroll through it, it uses arguably allot of screen real estate and. What if there will be 100 instances in the future? It is just very bad UX in my opinion. So in my opinion this issue is more of a QoL feature.

i would still like to see this.

**Comment by ChunkyProgrammer** [comment]
> I would also opt of just removing the list because if it gets too long like it is already, u'll need to scroll through it, it uses arguably allot of screen real estate and. What if there will be 100 instances in the future? It is just very bad UX in my opinion. So in my opinion this issue is more of a QoL feature.

I'm not sure what you mean by this

**Comment by ChunkyProgrammer** [comment]
> Something weird is going on here. When i type https:// the second / disappear.

Good catch! This issue also happens without this PR but I think I found the solution

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> > I would also opt of just removing the list because if it gets too long like it is already, u'll need to scroll through it, it uses arguably allot of screen real estate and. What if there will be 100 instances in the future? It is just very bad UX in my opinion. So in my opinion this issue is more of a QoL feature.
> 
> I'm not sure what you mean by this
Capture

i would opt for directing people to the offical instances page and remove showing the list all the time because what if there are 100 instances? This list would get very big that why i think its better to just remove it and direct people to the instances page. When they know what instance they want the autofill will help them out. Also with the auto fill u could still see every instance if u want when u type https://

**Comment by ChunkyProgrammer** [comment]
I believe I addressed your concerns @efb4f5ff-1298-471a-8973-3d47447115dc

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
if u misspell something u will still see the whole list 

used as example: yewtu.bee

**Comment by ChunkyProgrammer** [comment]
> if u misspell something u will still see the whole list
> 
> used as example: yewtu.bee

I added that intentionally

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
in my opinion it is still not desirable to see the list when u misspell something

another example: https://uptime.invidious.ioo

This one is on the bottom of the list if the list is very big u have to spend some time searching for it.

I think its also not desirable to just show the list when the field is empty because of the same reasons.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this intended behavior?


https://user-images.githubusercontent.com/73130443/135767181-77076158-44bb-4009-ba66-2634097afc73.mp4

**Comment by ChunkyProgrammer** [comment]
Nope, i made a spelling mistake

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Something seems wrong with the autofill after the last commit

https://user-images.githubusercontent.com/73130443/135768788-e8b54ebe-9952-42f0-b28a-2023b94a2049.mp4

**Comment by ChunkyProgrammer** [comment]
> Something seems wrong with the autofill after the last commit
> 
>  9elwgzKeaJ.mp4

Was able to reproduce issue in v 0.14.0 of FreeTube. It should be fixed now.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — DISMISSED** [review]
U did a splendid job on this! Thankyou for u patience with me 😄

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
OMG o.O i forgot to tell u to alter the tooltip text. Remove everything from Clear to from.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
I promise that u dont have to change anything anymore. LGTM!!!

**Review by Hiers — APPROVED** [review]
Everything lgtm, tested it and works as expected.

**Review by PikachuEXE — APPROVED** [review]
Tested that input locally and feels fine for me
But I rarely use the auto fill feature though

**Pull request merged**
