### PR TITLE
Scrollbar width setting

### LINKED ISSUE #3057: [Feature Request]: Customisable scrollbar size
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm using a remote to control Freetube on my TV

The remote has no scroll wheel or button. So I am forced to use the mouse to select the scroll bars (or use pg down but it's very unprecise)

The bar on the right is hard to get, the bar on the left (with the channel list) is ultra hard to select

### Proposed Solution

Please add options to allow customising the scrollbar size and making them always visible.

### Alternatives Considered

None

### Issue Labels

ease of use improvement, improvement existing feature, new optional setting 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by niceFont**
# Scrollbar width setting

## Pull Request Type

- [ ] Bugfix
- [X] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

Closes #3057 
## Description

This PR adds a new setting to the theme settings that allows the user to customize the size of the apps scrollbars.
It works by dynamically updating the `scrollbar-width` CSS variable using the value set in the store. 
The default value is 6px (like previously) and the slider allows a min value of 5px and a max value of 25px.
## Screenshots 

Before:
image

After:
image

## Testing 

I played around increasing and decreasing the width of the scrollbars to see which limits made most sense.
In the end, 15-25px looked good enough. I tried standing a bit further away from my monitor, trying to replicate what it would be like, staring at a TV.
Since this is subjective, I am open to adjusting the limits.
## Desktop

- **OS:** Pop! OS
- **OS Version:** 22.04 LTS
- **FreeTube version:** 0.18.0

### CODE REVIEW

**Review by PikachuEXE — COMMENTED** [review]
Tested and code looks fine to me
Though IMO why limit it to 5pm minimum just allow 0
(Don't change yet let's hear what others say)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Tested and code looks fine to me Though IMO why limit it to 5pm minimum just allow 0 (Don't change yet let's hear what others say)

0 would be cool.

I enabled Hide Side Bar Labels under Theme settings and im not sure if im seeing this right but it looks like the channels icons overlap with the scroll bar

https://user-images.githubusercontent.com/73130443/224552013-83c0f34a-fa83-4c6d-9c16-8b2359cfbf4c.mp4

**Comment by PikachuEXE** [comment]
> I enabled Hide Side Bar Labels under Theme settings and im not sure if im seeing this right but it looks like the channels icons overlap with the scroll bar

not really overlapping but 0 spacing
The style should be updated to have min spacing like 1/2/4px to scrollbar I guess?

**Comment by PikachuEXE** [comment]
The column is set to have width 60px
image

**Comment by PikachuEXE** [comment]
If some spacing really needed here is a change I just tested:
But not sure if this works for other width/settings
image

**Comment by niceFont** [comment]
Sounds good, I will add some space between the scrollbar and the content and also allow setting the width to 0px. Is the max width of 25px alright, or would you say it needs to be higher/lower?

**Review by PikachuEXE — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — CHANGES_REQUESTED** [review]
1. Need some space between scrollbar and the content
2. Allow 0px to be the minimum
3. When set to 25px subscriptions is not one word anymore

Capture

Edit: see nr 3

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @niceFont is it possible for u to implement the changes?

**Comment by osch** [comment]
This is insane cracy. Why can't the scrollbar width be configured? This must be a standard option since usual gui themes are ignored.

**Comment by absidue** [comment]
Because it was clearly abandoned for multiple months. Feel free to take over the PR and make the necessary changes if you want.

**Comment by absidue** [comment]
The way this pull request is currently made, the scroll bar overlaps on top of the content, if you make it any wider than the existing width.

**Comment by osch** [comment]
ah ok, now I understand the problem.

**Pull request closed without merging**
