### PR TITLE
Recognize more channel links

### LINKED ISSUE #1445: Featured Youtube Channel Link Does not open in Freetube
**Behavior of the program**
Featured Youtube Channel Link Does not open in Freetube . 
Receives following error:
"Unknown YouTube url type, cannot be opened in app"

**Expected behavior**
Channel link opens correctly.

**To Reproduce**
Go to 'https://www.youtube.com/c/sakumamio2/featured'

**Environment Information 
Windows 10
Freetube: v0.13.1 Beta

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Recognize more channel links
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #1445

**Description**
I updated the regex for detecting channel links to include other optional groups besides 'join' & it will open the relevent channel tab. This PR allows freetube to recognize channel links like /channel/{channelId}/about,  /channel/{channelId}/videos, /channel/{channelId}/featured & redirects to the relevant channel tab

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?

I used [regex101](https://regex101.com/) to test the regex and I was able to get the code to pass (to test the regex)
I also typed these channel links into the search bar (to test the redirect)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.1

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
Should I update this PR so it goes to the correct "sub path"? (ie. channelName/About will redirect to FreeTube channel about page)

**Comment by absidue** [comment]
The issue also happens when opening URLs with the `freetube://` URL scheme, please make sure this pull request covers that case as well. With the latest release (v0.14.0 Beta) it just shows a toast with "Unknown YouTube url type, cannot be opened in app". I would test if this pull request fixes that issue myself, however I haven't set up a FreeTube development environment yet.

URL with scheme: freetube://https://www.youtube.com/c/LinusTechTips/videos

Thanks.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This should also change the icon
https://github.com/FreeTubeApp/FreeTube/pull/1738

**Comment by PikachuEXE** [comment]
This branch name... makes me unable to pull

image

**Review by peepopoggers — APPROVED** [review]

**Pull request merged**
