### PR TITLE
Support taking video screenshots outside of Electron

### PR DESCRIPTION
**Pull request by absidue**
# Support taking video screenshots outside of Electron

## Pull Request Type

- [x] Feature Implementation

## Description

At the moment taking video screenshots is a feature exclusive to the Electron build of FreeTube, which means that it is not usuable in the FreeTubeAndroid fork. This limitation is not so much an intentional limitation but more so because the existing implementation relied heavily on Node.js and Electron APIs.

This pull request add support for taking screenshots with prompting for the save location outside of Electron. I don't have access to a FreeTubeAndroid compatible device to test this but hopefully it should work, as it uses the same prompt and save function as the data export. Saving to a specific folder is not supported outside of Electron as writing files without prompting the user requires more power than the web APIs offer and would require changes to FreeTubeAndroid's Kotlin code to replicate what we do with the Electron and Node.js APIs.

Notable changes:
- I removed the broken create subfolders functionality, this shouldn't affect anyone as the existing code would error when someone tried to set it up to save to a subdirectory.
- The `Saved screenshot` toast no longer shows the file path where the image was saved.
- Most screenshot settings are now shown and usuable outside of Electron, settings related to saving to the default folder are still hidden and ignored outside of Electron.

## Testing

Test that taking screenshots with the prompt for save path setting enabled works in both Electron and in Firefox (or FreeTubeAndroid if you have a compatible devices).
Also test that I didn't break saving to the default folder in Electron.

## Desktop

- **OS:** Windows
- **OS Version:** 10
- **FreeTube version:** cfc2d62f0bfc38257bfdd60a7d06d24763fa0011

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
- Electron, LGTM
- Browser, cant test due to error

https://github.com/user-attachments/assets/8e5a6440-b575-43d0-adb3-c1b73764ab52


- Phone, is it possible to provide an .apk file so i can try out

**Comment by PikachuEXE** [comment]
- `yarn dev`
- Test affected functionalities
- `yarn dev:web`
- Open the dev server URL in a web browser that doesn't support the Web File System API e.g. Firefox or Safari or if you have access to a FreeTubeAndroid compatible device you can test this pull request with that too.
- Test affected functionalities

Get similar errors w/ multiple IV instances...
This is happening on dev too
image

**Comment by absidue** [comment]
Ah great, looks like just after I submitted this PR, all Invidious instances switched to blocking cross-origin requests: (CORS column on this page: https://api.invidious.io/).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
instance doesnt seem to work for me as im getting the same error

**Comment by ChunkyProgrammer** [comment]
If an Invidious instance is working, it's probably using https://github.com/iv-org/invidious/pull/4985 which disabled CORS so it will be almost impossible to test the web build at this time. I'll approve this since the electron build is working.

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
