### PR TITLE
Fix confusing zoomin shortcut

### LINKED ISSUE #1247: Cannot zoom back out after zooming in (CTRL+ not working) [Electron issue]
**Behavior of the program**
Cannot zoom back in after zooming out.
Most likely due to electronjs.

**Expected behavior**
Zoom out works only.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Use CTRL & MINUS
2. The window will size down
3. Now try and do CTRL & PLUS
4. It does not zoom back in

**Environment Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - FreeTube version: v0.12.0 Beta
 - Installation Method (If applicable): AppImage
 - Primary API Used: Local API ??

**Solution**
You can add a custom function w/ eventlistener that takes CTRL+ and zooms the page in when activated.

### PR DESCRIPTION
**Pull request by vallode**
---
Fix confusing zoomin shortcut
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
Closes #1247 

**Description**
Adds a "hidden" global shortcut for zooming in (ctrl + equals) that should fix some of the confusion over the zoomin shortcuts, also adds zoom shortcuts using numpad (numpad +, -, and 0) to mirror browser behaviour.

**Testing (for code that is not small enough to be easily understandable)**
Zoom in and out a bunch with keyboard shortcuts :)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - OS Version: [e.g. 22] Debian
 - FreeTube version: [e.g. 0.8] upstream/development

**Additional context**
I tried to do some digging into how we could sync UI scale with the zoom properly, sadly I didn't come to any clear conclusions. Electron only sends an event on changing zoom via mouse wheel. Annoying!

### CODE REVIEW

**Review by absidue — CHANGES_REQUESTED** [review]
Could you please make the zoom shortcuts work with the numpad `+` (`numadd`), `-` (`numsub`) and `0` (`num0`) keys as well, to replicate web browser behaviour? https://www.electronjs.org/docs/latest/api/accelerator#available-key-codes

**Review by absidue — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]
Test on MacOS 12.4, M1 Mac
No numpad, so some combinations (`accelerator`) cannot tested

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://user-images.githubusercontent.com/73130443/174500991-b075ebc5-ccb4-4e54-8925-b81ee2a2713e.mp4

@vallode is it possible to fix the slider %?

**Comment by PikachuEXE** [comment]
Do you mean that you expect the slider to also update its value when UI scale is changed via shortcuts?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE yes thats what i meant. Sorry for bad description i was kinda tired😬

**Comment by vallode** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I mentioned in the PR:

> I tried to do some digging into how we could sync UI scale with the zoom properly, sadly I didn't come to any clear conclusions. Electron only sends an event on changing zoom via mouse wheel. Annoying!

It's a complicated issue, we can open another issue for it and I'll try to get around to it eventually but I do see it as out of scope for this PR for now.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ok sure, one more thing before i approve. Can u create a PR in our docs repo and add the shortcuts to the list.

**Comment by vallode** [comment]
#2341 new issue for the sync

> add the shortcuts to the list.
keyboard-shortcuts.md mostly refers to shortcuts that are used while watching a video, these new shortcut additions really are just a way of making sure we are adhering to all _standard_ shortcuts on the system. Is there a need to add 5 new shortcuts for zooming in and out? I just see it as standard/non-freetube specific behaviour.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
While i do agree with your argument. I still think it is important to inform the users about it who dont know it exists.

While this functionality sounds logical to u and i to be the default, i've learned that u cant just assume that everyone has the same thought process.

**Comment by vallode** [comment]
> While i do agree with your argument. I still think it is important to inform the users about it who dont know it exists.
> 
> While this functionality sounds logical to u and i to be the default, i've learned that u cant just assume that everyone has the same thought process as u and i.

https://github.com/FreeTubeApp/FreeTube-Docs/pull/27

Added a new section on the more browser-like shortcuts in the docs.

**Pull request merged**
