### PR TITLE
Update electron to 16.2.5

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
N/A

**Description**
Update electron to [16.2.5](https://github.com/electron/electron/releases/tag/v16.2.5)
**Multiple** CVE fixes included
Update electron to [16.2.4](https://github.com/electron/electron/releases/tag/v16.2.4)
**Multiple** CVE fixes included
Update electron to [16.2.3](https://github.com/electron/electron/releases/tag/v16.2.3)
CVE fixes included

**Screenshots (if appropriate)**
N/A

**Testing (for code that is not small enough to be easily understandable)**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 12.1
 - FreeTube version: e29d041a91fe78e96b62ac8cd61d8d8a78797ab7

**Additional context**

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by ChunkyProgrammer — DISMISSED** [review]

**Comment by PikachuEXE** [comment]
Who else is active ._.

**Comment by PikachuEXE** [comment]
Who else is active ._.

**Comment by PikachuEXE** [comment]
Updated electron to [16.2.4](https://github.com/electron/electron/releases/tag/v16.2.4)
**Many** CVE fixes included

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — DISMISSED** [review]

**Comment by PikachuEXE** [comment]
Updated electron to [16.2.5](https://github.com/electron/electron/releases/tag/v16.2.5)
**Multiple** CVE fixes included

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Pull request merged**
