### PR TITLE
[Feature] Search results based on region/language 

### LINKED ISSUE #1133: Search results based on region/language
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Yes. Since the results displayed are from other regions, the content displayed is mostly not relevant.

**Describe the solution you'd like to see implemented**
In the same way as it is already possible to select the region for the "Trending" videos, the user could have the option to select the country by which he wants to filter the results.

**Describe alternatives you've considered**
I tried to see if the results would change depending on the IP location, but there was no change. North and South American IP's had the same results displayed.

**Screenshots**
Here is a screenshot for a simple search for the term Github. The results are as diverse as possible and none seem to be related to the language freetube is using (portuguese).

<details><summary>Click me</summary>

ksnip_tmp_XAfHMX
</details>

**Additional context**
The invidious seems to have an option to do something similar, using the `hl:LOCALE` option in the search bar filters the results based on what was requested. [But this is only limited for some regions](https://github.com/iv-org/invidious/issues/476).

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Search results based on region/language 
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
closes #1133

**Description**
I modified calls to local and invidious search to include extra parameters:

- node-ytsr has **hl**(language) and **gl**(region) options that allow language code and country code to be passed to searches

- Invidious api accepts **language** and **region** parameters

**Screenshots (if appropriate)**
I added search region & search language options
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

1. Search something
2. Clear search cache
3. Change location
4. Search again
5. Clear search cache
6. Change language
7. Search again
8. Compare results
9. Repeat for other api

### LOCAL API TESTS
image
image
image
 
### INVIDIOUS API TEST
image
image
image

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.2

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
The local api version is definitely working. I am not too sure about the invidious one. It does give different results with same region but I think I'm supposed to use a 'hl' tag but I tested it and it doesn't translate channel names that should be translated. While LocalApi shows localized channel names (ex. I translated my channel name into french and changing language to french would show me the french one)

**Comment by ChunkyProgrammer** [comment]
I think it might be worth combining search location & language with trending location & language. Depending on if this pr gets merged https://github.com/FreeTubeApp/yt-trending-scraper/pull/6

**Comment by fabianski7** [comment]
It's not working for me.
The search result is always displayed according to my IP address, no matter which region I choose in freetube. The API doesn't change the results either.

[Search with USA IP address but with Brazil region](https://i.imgur.com/v6yrYl2.png)

[Search with the IP address of Brazil but with the USA region](https://i.imgur.com/GzMGfOI.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just checking in what is the progress of this?

**Comment by ChunkyProgrammer** [comment]
> Hi @ChunkyProgrammer just checking in what is the progress of this?

I looked into it some more and sadly, it doesn't seem to be possible to get this feature to work as intended

**Pull request closed without merging**
