### PR TITLE
Update of Portuguese translation.

### PR DESCRIPTION
**Pull request by Hiers**
---
Update of Portuguese translation.
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Description**
Fixed some mistakes and translated missing strings.

**Desktop (please complete the following information):**
 - OS: Artix
 - OS Version: N/A
 - FreeTube version: 0.13.2

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did u try to use Weblate? In Weblate u can translate it and it will be merged automatically. Its better then waiting for this PR to be merged

**Comment by Hiers** [comment]
I didn't like using Weblate because it just gave you strings with little to no context, so I always just changed the file itself while FreeTube was running so I could see the changes and how they felt. But I get your point, I think I'll still change the file itself like before, but next time I'll take those changes and push them through Weblate instead.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah yes i get that it can be a confusing with little to no context. No worries just wanted to let u know.

**Comment by GilgusMaximus** [comment]
Just want to inform you that pasting it into Weblate will probably get you faster to this being included than creating a PR, as we are usually trying to merge in the oldest prs first. And some have new string inside, so there would likely be a merge conflict with your changes

**Comment by Hiers** [comment]
If it would cause merge conflicts then I'll push these changes through weblate and close this pr.

**Pull request closed without merging**
