### PR TITLE
New Design

### LINKED ISSUE #1452: Add option for rounded grid elements within app
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It is a low-priority feature request, but should be easy to impliment.

My request would be a settings option to change the border radius of page elements (pictures below).
Would be optional.

It could be implimented by using a css variable which is passed into `border-radius: var(x)` for each tiling element (plus video player with `overflow:hidden` and the same method.
The same could be done for thumbnails too with another option.

**Screenshots**
(Tiles) Before:
image

(Tiles) After:
image

(Thumbnails) Before:
image

(Thumbnails) After:
image

**Additional context**
If one is chosen for addition, tiles is of more importance.

### PR DESCRIPTION
**Pull request by dragosnfy**
---
New Design
---

**Description**
Integration with the Design-Tweaks fork

**Pull Request Type**
- [ ] Bugfix
- [x] Feature Implementation

**Screenshots**

<table border="0" width="100%" border-color="red">
<tr><td width="50%"></td>
<td></td></tr>
</table>

**Related issue**
closes #1452

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
Exclude changes to workflow & the ReadMe?

**Comment by dragosnfy** [comment]
Of course haha! It's not the final edit and lots of parts can't even be integrated yet. @GilgusMaximus suggested I should make a new branch and PR and make edits, so that's why. Sorry for the confusion lol

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Q1: will there be a toggle to switch to rounded corners or the default design in the settings?

Q2: Will there be changes that are not theme based? So these will effect the whole application doenst matter which theme u select.

**Comment by dragosnfy** [comment]
A1: I proposed that but I'm not in control of the decision... only my own fork, so that depends on what others want.
A2. Technically yes, for example the width of the video gallery, which is larger now. But this pr has lots of new changes... so I don't know which ones will or will not be implemented.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This PR is getting blocked by this one https://github.com/FreeTubeApp/FreeTube/pull/1461 right?

**Comment by dragosnfy** [comment]
yea, this one basically contains that one lol

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Of this issue also contains it, i think its better to close that one.

**Comment by dragosnfy** [comment]
closed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Btw u have to add closes #1452

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
maybe it closes #1293 also not sure

**Comment by dragosnfy** [comment]
Thank you! I added that and now it says it will be closed if this gets merged

**Comment by peepopoggers** [comment]
Give a rundown of what has changed in this pr

**Comment by peepopoggers** [comment]
Also have been looking at your version. I really think that your changes should be split into several different pr's. Adding a monolith pull request like this one complicates and makes it hard to review all the changes. Also your version seems very experimental. I think moving changes slowly through seperate non-conflicting pr's would be a better idea.

**Comment by dragosnfy** [comment]
Alright

**Comment by peepopoggers** [comment]
Agreed

**Comment by PrestonN** [comment]
Hey there @dragosnfy. I know we've talked a bit about these design changes in our Matrix channel. While I'm still interested in possibly implementing some of these changes, I'm going to go ahead and close this PR for now.

Looking through your changes, it looks like they were made outside of our existing Vue component structure and also includes your changes made specifically for the fork you've created. The changes made for your specific fork will need to be removed and your existing code will need to be reworked to be inside of our components in order for us to be able to merge this. This may take a while which is why I've decided to close this. You are more than welcome to create a new PR once these changes are ready.

Myself as well as some of the other contributors will be more than happy to help lead you in the right direction for doing this properly. You're already active in our Matrix channel so you already know where to find us. During the process, we can maybe break down this PR into smaller sections so that we can make sure everything is implemented properly. The other issue with PRs this large is that it can disrupt the other PRs currently out there and can force other contributors to restructure their PR because of the large changes that we've included. Breaking this down can help prevent that as well.

I hope you understand my decision with this and I don't want to sound too harsh about it. The designs you did are genuinely good and I'd like to look at them more, however we'll have to do a lot before they'll be ready to include upstream. Like I said, I'm available to help you with this process if you'd like.

**Pull request closed without merging**
