### PR TITLE
Change to only consider currently live broadcasts as livestreams.

### PR DESCRIPTION
**Pull request by DuaneJaspers**
---
Change to only consider currently live broadcasts as livestreams.
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
#704 

**Description**
In the current situation, both live streams that are already finished and live streams that are still streaming are considered as live content. So for live streams that are finished things like watch history and comments aren't available, and the live chat is empty. I changed it so that past broadcasts are considered normal uploads so watch history, downloads and comments become available.

**Screenshots (if appropriate)**
***before***
Before
***after***
After

**Testing (for code that is not small enough to be easily understandable)**
I've tested this for normal videos, past broadcasts, and live broadcasts. This all seems to work as expected. 

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.9.1

### CODE REVIEW

**Comment by GilgusMaximus** [comment]
Thanks for the contribution. So the code itself looks fine and works fine.

However with this change in place, it would be the perfect chance to add a string saying 'Streamed on the x. of x xxx'. Just to make it more consistent with YouTube. Something similar to what is in place for normal videos. 

If you want to do it, go ahead, otherwise I'll look into it.

**Comment by DuaneJaspers** [comment]
That makes sense!
I'll try to add other variants like "Premiered", "Started streaming on", and "Streamed on" to be totally consistent with YouTube.

**Comment by DuaneJaspers** [comment]
I've added the "Started streaming on" (for streams that are still live), and "Streamed on" (for streams that are finished). 
I could not find a way to determine whether a video was once a premiere to change the string to "Premiered Oct 19, 2020".

**Review by PrestonN — APPROVED** [review]
I wanted to do a bit of testing myself before I approved this, as I recalled a reason I did it this way.  Something about the formats of a recent stream not behaving properly.  Testing it out here though I can't seem to find an issue, so it looks like we're good.  Thank you very much!

**Pull request merged**
