### PR TITLE
Fix nightly build app startup caused by missing `tslib`

### LINKED ISSUE #1722: blank page
**Behavior of the program**
when starting up the entire program is white(blank

**Expected behavior**
load

**To Reproduce**
open 1201 or 1202

**Screenshots**

Screenshot from 2021-09-20 06-35-03

**Environment Information (please complete the following information):**
 - OS: Solus
 - OS Version: [4.2]
 - FreeTube version: [1201, 1202]
 - Installation Method (AppImage]
 - Primary API Used: [Local API]

**Additional context**
this is likely a cause of the change from npm to yarn?, was tested on two different machines

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Important note**
We may remove your pull request if you do not use this provided PR template correctly.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
closes #1722

**Description**
App start up caused by `@freetube/youtube-chat` requiring `tslib` but package not found
This seems to be caused by `@freetube/youtube-chat` declaring `tslib` in `devDependencies` not `dependencies`

**Screenshots (if appropriate)**
N/A

**Testing (for code that is not small enough to be easily understandable)**
This PR will start a build and the built artifacts can be used for testing

**Additional context**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I have tested the [artifact for MacOS](https://github.com/FreeTubeApp/FreeTube/actions/runs/1252405514) and it's loading as expected

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lol the issue u linked to this is closed.

**Comment by PikachuEXE** [comment]
Ya I have also tried the recent nightly builds and I can reproduce the issue myself

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Ya I have also tried the recent nightly builds and I can reproduce the issue myself

I did the same. I've got the same results.

**Comment by PikachuEXE** [comment]
I think he might be using 1203 which is a test build started by this draft PR
So I reopened that issue

**Comment by ChunkyProgrammer** [comment]
Is #1689 related to the issue that's fixed? Also, since this PR is just updating dependencies, maybe consider updating nedb-promises to ^5.0.1 which will fix #1435

**Comment by burny0202** [comment]
> Is #1689 related to the issue that's fixed? Also, since this PR is just updating dependencies, maybe consider updating nedb-promises to ^5.0.1 which will fix #1435

installing tslib but #1689 still persists

**Comment by PikachuEXE** [comment]
#1689 is **not** related to this PR
And this PR does **not** about updating dependencies

**Comment by PrestonN** [comment]
You should be able to use the live package now. I've merged over your changes and published the update.

**Comment by PikachuEXE** [comment]
PR updated to use
`@freetube/youtube-chat@^1.1.2`

Will test app building locally once

**Comment by PikachuEXE** [comment]
I build locally on this PR's branch via `npm run build`
And the app can be opened and is working fine on MacOS

**Pull request merged**
