### PR TITLE
Fix the localised description containing broken URLs

### LINKED ISSUE #2578: [Bug]: Words are filtered out in video title if there is a # before the word
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Go to https://www.youtube.com/watch?v=GpciEQHTTME 
2. See title is `Where Does the` (Original->`Where Does the #Hashtag Symbol Come From?`)

### Expected Behavior

I want to see the full title of the video.

### Issue Labels

visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/7ed47749f799e1905d6eadf82db300de071620be

### Operating System Version

Win10 21H1

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by absidue**
---
Fix the localised description containing broken URLs
---

**Pull Request Type**

- [x] Bugfix

**Related issue**
Follow up to #2535
Closes #2578

**Description**
This pull request fixes the truncated links in the localised video description, making them valid URLs so that `autolinker` can properly link them.

**Screenshots**
Before:
before

After:
after

**Testing**
https://www.youtube.com/watch?v=zcchDu7KoYs

This video's description has a bunch of tricky things like timestamps, links to other videos, the special URL `http://www.youtube.com/approachingnirvana` and the lttstore link has utm tracking parameters.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.17.1

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]
Tested locally with
https://www.youtube.com/watch?v=zcchDu7KoYs

**Comment by absidue** [comment]
Added a fix for hashtags in the title into this PR as well.

**Review by PikachuEXE — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by PikachuEXE** [comment]
@ChunkyProgrammer we need your power

**Review by ChunkyProgrammer — APPROVED** [review]
LGTM

**Pull request merged**
