### PR TITLE
Switch from npm to yarn as package manager

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Important note**
We may remove your pull request if you do not use this provided PR template correctly.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
[Recent Build Failures](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml)
Due to `cb() never called!` (Example issue in npm: https://github.com/npm/cli/issues/417)

**Description**
Use `yarn` (1.x) instead of `npm`
Use `yarn.lock` instead of `package-lock.json`
Use `yarn install --frozen-lockfile` instead of `npm ci`

**Screenshots (if appropriate)**
Takes less time to install packages
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Additional context**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Build workflow passed
image

https://github.com/FreeTubeApp/FreeTube/actions/runs/1227975914

**Comment by PikachuEXE** [comment]
Nightly builds are still failing

image

**Review by Hiers — DISMISSED** [review]
LGTM

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by jasonhenriquez — CHANGES_REQUESTED** [review]
There are multiple places in the code that use npm that have not been altered for this PR. tasks.json, now-unnecessary .gitignore values, and an outdated CONTRIBUTING.md file to name a few.

**Comment by PikachuEXE** [comment]
@jasonhenriquez 
`tasks.json`: I created this PR to **only** update the package installation step
We would still use `npm` for running scripts such as `npm dev` & `npm dev-runner` in `tasks.json`

`.gitignore`: Can you share which values look unnecessary after we switch to `yarn` for package installation?

`CONTRIBUTING.md`: 
The content for https://docs.freetubeapp.io/development/getting-started/ seems to be in another project.
We should update it but we can do that afterward.

Is there any other update that should made for this `npm` > `yarn` switch? (Again, package installation step only)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE ready for review?

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
Yes
Nothing else needs to be changed
This only affects package installation step as I said

**Comment by jasonhenriquez** [comment]
@PrestonN: just to be sure that this will fix the problem, is there a way to test this on the main repository before merging?

**Comment by PikachuEXE** [comment]
@jasonhenriquez 
You want to run it once?
[I have done that already](https://github.com/FreeTubeApp/FreeTube/actions/runs/1227975914)

**Review by jasonhenriquez — APPROVED** [review]
After a good deal of testing and looking into it, I see no harm in it, and there are benefits. LGTM!

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by Hiers — APPROVED** [review]

**Comment by PikachuEXE** [comment]
[Nightly build working again!](https://github.com/FreeTubeApp/FreeTube/actions/runs/1250239413)

**Pull request merged**
