### PR TITLE
update vue2 to latest

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
update vue2 to latest
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Dependencies

**Description**
Update vue2 to latest version of vue2 (migrating to vue3 would probably be a good idea in the future)

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
package built without errors `yarn run dev`

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - FreeTube version: 0.17.1

### CODE REVIEW

**Review by PikachuEXE — DISMISSED** [review]
Anyone consider upgrading to vue 3?
Pros and cons compared to vue 2?

**Comment by absidue** [comment]
@PikachuEXE Vue 3 has better performance and smaller package size than Vue 2, however we will need to make a bunch of code changes to get FreeTube Vue 3 compatible (Different APIs, breaking changes, rewriting the stores in the Pinia format, etc).

**Review by absidue — COMMENTED** [review]
please make the changes listed in the vue 2.7 upgrade guide https://github.com/vuejs/vue/blob/main/CHANGELOG.md#upgrade-guide (specifically the vue-loader and vue-template-compiler ones). vue-router should probably be updated to the latest vue 2 compatible version as well.

**Review by PikachuEXE — COMMENTED** [review]
Should we test it for 1 week first?

**Comment by ChunkyProgrammer** [comment]
superlint is failing because of "deep" selector. I think there's still some more configuration that we'd need to do. Maybe instead of linting we could just make sure the files are valid? Or at the very least we should add a dev dependency that will lint yaml, css and sass files.

**Comment by absidue** [comment]
the deep selector is a vue specific thing. unless superlint has some setting to support vue specific css, we will need to exclude css files from the superlint checks.

**Comment by PikachuEXE** [comment]
Test paused until lint issue fixed

**Comment by ChunkyProgrammer** [comment]
> Test paused until lint issue fixed

It could still be merged with the lint issue

**Comment by PikachuEXE** [comment]
It's actually not started since I forgot to merge that branch for my custom build last time lol
Starting now

**Comment by PikachuEXE** [comment]
Merge conflict again...
Will mark as pass once conflict resolved

**Review by PikachuEXE — APPROVED** [review]

**Review by absidue — APPROVED** [review]

**Pull request merged**
