### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ovari**
https://github.com/FreeTubeApp/FreeTube/issues/1653

### CODE REVIEW

**Comment by ovari** [comment]
Is there something we need to do so this can be merged? Thank you

**Review by jasonhenriquez — APPROVED** [review]
> Is there something we need to do so this can be merged? Thank you

You only have to be patient and ready to make required changes as time goes on. Unfortunately, it is a busy time, and we're doing as much as we can to test & approve pull requests.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by peepopoggers** [comment]
Just a thought, how can you translate the .desktop file? thanks.

**Comment by ovari** [comment]
> Just a thought, how can you translate the .desktop file? thanks.

https://github.com/flathub/io.freetubeapp.FreeTube/blob/master/io.freetubeapp.FreeTube.desktop

This link should be in this merge request.

**Review by PikachuEXE — APPROVED** [review]

**Comment by ovari** [comment]
Thank you all for merging this request.

Are there different reviewers for the Flathub repository merge requests, say https://github.com/flathub/io.freetubeapp.FreeTube/pull/58?

Thank you once again

**Pull request merged**
