### PR TITLE
added slovak as an active language

### LINKED ISSUE #873: [Translations]Finished the Slovak Translation on weblate.
Just letting you know, that I finished the Slovak translation from around 30% to 100. There are some errors when we use different tenses where English uses only one, so there are problems translating it, but nothing that can not be easily fixed.
https://hosted.weblate.org/projects/free-tube/translations/sk/

### PR DESCRIPTION
**Pull request by kubo6472**
---
Closes #873 
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

### CODE REVIEW

**Comment by kubo6472** [comment]
if I understand correctly, this should trigger weblate updating the file with translations

**Comment by kubo6472** [comment]
okay, I added the file from weblate manually

**Comment by kubo6472** [comment]
I rolled back the change of adding the language file manually since it got added automatically here.

**Comment by PrestonN** [comment]
LGTM. Thank you!

**Pull request merged**
