### PR TITLE
Collapsible Settings Sections

### PR DESCRIPTION
**Pull request by jasonhenriquez**
---
Collapsible Settings Sections
---

**Pull Request Type**
- [x] Feature Implementation

**Related issue**
N/A

**Description**
Visual / ease-of-use overhaul of the settings headings into collapsible sections. This should make traversing the settings page easier and save users some scrolling time.

**Screenshots (if appropriate)**
Light mode, default theme: 
Screenshot_20210914_125231

Dark mode, default theme:
Screenshot_20210914_125357

Black mode, default theme:
Screenshot_20210914_125451

Light mode, default theme, on open:
Screenshot_20210914_125317

**Testing (for code that is not small enough to be easily understandable)**
Mostly styling changes -- everything works just as well.

**Desktop (please complete the following information):**
 - OS: OpenSUSE
 - OS Version: Tumbleweed
 - FreeTube version: bleeding edge

**Additional context**
I considered implementing auto-scrolling down to the bottom of a given section after it is opened. I decided against because it may not be behavior people want. I welcome your thoughts on this decision and am still considering adding this functionality.

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not tested yet but would this work fine with the accessibility pr?

**Review by ChunkyProgrammer — COMMENTED** [review]
Not tested yet but I skimmed through the code and it looks good

**Comment by jasonhenriquez** [comment]
> Not tested yet but would this work fine with the accessibility pr?

If you are asking about merge conflicts, I did not directly touch the settings section at all in the Accessibility Improvements PR. If you are asking if this is sufficiently accessible, I believe it has no such issues either. The triangle from `<details>` is occluded because of the usage of `display: block`, but the `--primary-color` `<hr>` indicator below each opened tab should be a sufficient indicator.

**Review by ChunkyProgrammer — APPROVED** [review]
LGTM

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
NICE JOB!

**Review by PikachuEXE — APPROVED** [review]
Tested locally

**Comment by peepopoggers** [comment]
:+1: really good job!!!

**Pull request merged**
