### PR TITLE
Added ability to change volume level with scroll wheel

### LINKED ISSUE #573: Adjusting volume with scroll wheel is not working.
**Behavior of the program**
When I hover over the volume and try to adjust it with the scroll wheel it just scrolls the page. I've read in a closed issue that this feature was supposed have been implemented.

**Expected behavior**
Hovering over the volume and using the scroll wheel should increase/decrease volume.

**To Reproduce**
1. Open video
2. Hover over volume bar
3. Scroll up or down

**Desktop (please complete the following information):**
 - OS: Manjaro
 - OS Version: 20.1.1 Mikah
 - FreeTube version: v0.8.0 Beta

### PR DESCRIPTION
**Pull request by TDDR**
---
Added ability to change volume level with scroll wheel
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
Fixes #573 

**Description**
As the title suggests, I was finally able to figure out how to enable volume scroll on hover. Now, when the user hovers over the volume panel the user can change the volume with a wheel scroll. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1909
 - FreeTube version: 0.9

**Additional context**
There is one thing that I found in testing that I am unsure if you would consider it a bug or a feature. If the user clicks on the mute button, that locks out the ability to wheel scroll the volume back on. The user must manually click the mute button again to unmute.

### CODE REVIEW

**Comment by Synkky** [comment]
Apparently, the mouse wheel still changes the volume while the sound is muted.
If you are at 50% volume, mute, scroll up and unmute, you can put it at 100% and can easily have it blasting your ears accidentally.
Not mandatory (I'm not in charge anyway), but try to make a condition that prevents the mousewheel from modifying the sound if the video is muted.

**Comment by GilgusMaximus** [comment]
But that depends on the user. I would expect the program to do that honestly.

**Comment by Synkky** [comment]
Yeah, I guess it does differ from person to person, it's probably fine as it is.

**Comment by TDDR** [comment]
Thanks for catching that Synkky. That should be an easy enough condition to check for, but I think I'll leave it up to PrestonN to decide if it's a bug or a feature.

**Comment by PrestonN** [comment]
Apologies for the delayed response on this.

I would say that if the volume is muted and the user scrolls up, this should unmute the volume and set it to 0.05 (whatever is the lowest increment).  Ideally it shouldn't be changing the volume in the background where the user doesn't understand what's being changed.  This should be fairly simple to implement.

Let me know if you have any questions about it.

**Comment by TDDR** [comment]
Finished those amendments. Let me know if it's up to par!

**Comment by TDDR** [comment]
Sorry, I messed up my local branches. I'm gonna re-submit a PR for this.

**Pull request closed without merging**
