### PR TITLE
Fix #1774 - Dropdown doesn't match theme in dark mode

### LINKED ISSUE #1774: Dropdown doesnt match theme in dark mode
**Is your feature request related to a usage problem (not a bug)? Please describe.**
There is one dropdown in the playlists menu that doesnt matches the theme.

**Describe the solution you'd like to see implemented**
Match dark theme.

**Describe alternatives you've considered**
None.

**Screenshots**

Screenshot (232)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by jilv220**
---
Fix playlist dropdown menu theme not match
---

**Pull Request Type**
- [x] Bugfix

**Related issue**
 Closes #1774

**Description**
- Change the side nav color in dark mode to match the dropdown menu color 
- Change the side nave color in black theme to make the border more recognizable

**Screenshots (if appropriate)**
new_sidenav_color
new_sidenav_color_2

**Desktop**
 - OS : Arch Linux 
 - Kernel : 5.17.3-256-tkg-pds
 - FreeTube version :  v0.16.0

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — CHANGES_REQUESTED** [review]
1. Its almost invisible in the black theme
2. in the dark theme the items in the list dont get highlighted anymore

on another note: dont just ignore the template. u can just remove headers that are unnecessary to you and fill in the other parts. See [example](https://github.com/FreeTubeApp/FreeTube/pull/2200)

**Comment by jilv220** [comment]
> 1. Its almost invisible in the black theme
> 2. in the dark theme the items in the list dont get highlighted anymore
> 
> on another note: dont just ignore the template. u can just remove headers that are unnecessary to you and fill in the other parts. See [example](https://github.com/FreeTubeApp/FreeTube/pull/2200)

I fixed the highlight in dark theme, but I don't know how should i fix the invisible problem in black theme. 

The way I proposed is to change the `background-color` to some lighter black/gray.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
we could definitely give that a try

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
Looks Good To Me, Thank you for your contribution!

Edit: We need 3 reviewers in order to get this merged but dont let that discourage u in contributing more if u want.

**Review by PikachuEXE — APPROVED** [review]
Tested dark & black & light mode
Video for dark mode on fixed menu:

https://user-images.githubusercontent.com/1018543/168192641-cab68d51-a14b-4c58-a88e-c5ec872b1667.mov

**Review by ChunkyProgrammer — APPROVED** [review]
Lgtm

**Pull request merged**
