### PR TITLE
Make showToast a helper

### PR DESCRIPTION
**Pull request by absidue**
# Title

## Pull Request Type

- [x] Refactor

## Description
This pull request refactors the showToast function from a store action to a normal function that can be imported and used like any other function.

## Testing 
Easy ways to get a toast to show up:
- switch profile
- set or unset the default invidious instance
- have autoplay enabled and go to the end of a video, you'll get the countdown toast

## Desktop

- **OS:** Windows
- **OS Version:** 10
- **FreeTube version:** 0.17.1

### CODE REVIEW

**Comment by absidue** [comment]
You can ignore the codeql alerts for now as they will be fixed in #2685.

**Comment by PikachuEXE** [comment]
Does that mean this should be reviewed AFTER #2685 is merged?

**Comment by absidue** [comment]
> Does that mean this should be reviewed AFTER #2685 is merged?

Yes.

**Comment by absidue** [comment]
This is read for review now.

**Review by PikachuEXE — APPROVED** [review]
Tested locally

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Pull request merged**
