### PR TITLE
Change icon color of FT logo 

### LINKED ISSUE #4020: [Feature Request]: Change icon color of FT logo on About page based on set theme
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Depending on what theme u pick the FT icon in the top bar will change color. This isnt the case for the FT icon on the about page. Some themes are not compatible with the default FT icon. So it would make sense to use the same icon color everywhere based on the set theme.

### Proposed Solution

Make icon consistent with the icon color of the set theme

### Alternatives Considered

Dont implement this

### Issue Labels

visual improvement

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AnshuMishra01**
Change icon color of FT logo

Pull Request Type

 Feature Implementation
Related issue

closes #4020

Description
Changed icon color of FT logo on based on set theme

Available Methods :-

As far as I can see, you have three choices:

1) I used an online tool to vectorize our existing logo. You can add it to _icons (our current icon SVG is using a raster image, which doesn't work for this), add it inline to the template, and use the fill CSS property to dynamically change the color to the --primary-text-color for that theme. logoBlack

2) You can create different versions of this logo icon by changing the fill="#ffffff" to the primary text color for the given theme and use those.

3) You can use an editor like GIMP to create logo images for the themes missing them (with the fill color of that theme's --primary-text-color) (probably more effort than two).

Implemented 2 option :)

### CODE REVIEW

**Comment by absidue** [comment]
Please remove the yarn error log and revert the addition of `yarn` as a dependency.

**Comment by absidue** [comment]
I do like the idea of dynamically changing the colour :)

**Comment by AnshuMishra01** [comment]
ok Sure

**Comment by AnshuMishra01** [comment]
Its done :)

**Comment by absidue** [comment]
Ideally the logo on the about page should match the one in the navigation bar. Unfortunately this current approach, forces the logo to always be one single colour, so you loose the blue and red colors, which makes this pull request a branding change.

**Pull request closed without merging**
