### PR TITLE
Sync theme between windows

### PR DESCRIPTION
**Pull request by vallode**
---
Sync theme between windows
---

**Pull Request Type**
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
N/A

**Description**
Finally moves baseTheme, mainColor, secColor logic away from localstorage and into vuex so that we can seamlessly sync them between windows and lower code overhead. It also syncs the expandSideBar setting between windows.

**Screenshots (if appropriate)**
N/A

**Testing (for code that is not small enough to be easily understandable)**
Open several windows and flip between themes to your hearts content.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian
 - OS Version: [e.g. 22] 11
 - FreeTube version: [e.g. 0.8] 0.16

**Additional context**
This will help merge #1800 as there is an issue there with themes resetting and not syncing properly. Since this cleans up the logic it will make it easier to debug that.

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So if i understand correctly this one needs to be merged first in order to get #1800 merged right?

**Comment by vallode** [comment]
> So if i understand correctly this one needs to be merged first in order to get #1800 merged right?

Yes, this will make my other PR simpler to debug. :)

**Review by PikachuEXE — APPROVED** [review]
Briefly tested locally with 2 windows
Seems fine

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
Why aren't you on the reviewer list o.0

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
everything works like intended. The only thing that is bugging me is this https://github.com/FreeTubeApp/FreeTube/pull/1800#issuecomment-943821753 but i guess that ur answer would be the same as last time https://github.com/FreeTubeApp/FreeTube/pull/1800#issuecomment-944066397

**Comment by vallode** [comment]
> everything works like intended. The only thing that is bugging me is this [#1800 (comment)](https://github.com/FreeTubeApp/FreeTube/pull/1800#issuecomment-943821753) but i guess that ur answer would be the same as last time [#1800 (comment)](https://github.com/FreeTubeApp/FreeTube/pull/1800#issuecomment-944066397). If that the case, i'll approve after ur response

Is that issue you were facing in #1800 happening with this PR also? If it is _not_ I hope we can merge this in and we test the other PR with these changes once I debug a bit more there. Thanks for your help!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The issue im facing is linked in the video of the comment

**Comment by vallode** [comment]
> Not sure if we're talking about the same issue. U can see the issue im facing in the video that is linked in the comment

Ah I see now, I did misunderstand yeah.

That issue should no longer be an issue with the database changes that were brought in a bit back, I'll take a look at it when I'm working on the PR again and make sure I fix it (if it still exists) since I agree it's not nice :)

**Comment by vallode** [comment]
Just to be clear @efb4f5ff-1298-471a-8973-3d47447115dc I don't think any changes are needed on this PR, I meant when I return to work on the next one. Are there any changes outside of that?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Outside of that? No. I'll approve the pr!

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by vallode** [comment]
We should probably also remove the changes requested label so Chunky knows they can review this :wink:

**Review by ChunkyProgrammer — APPROVED** [review]
Lgtm

**Pull request merged**
