### PR TITLE
Store Revamp / Full database synchronization across windows

### LINKED ISSUE #1919: "Save video" fetaure is buggy when using multiple windows
**README: Before You Submit Your Issue**
Done !

**Behavior of the program**
'Save video' feature is bugged when using multiple windows : saved video dont appear in other windows

**Expected behavior**
Saving a video should work, whether you use one or multiple windows

**To Reproduce**
1. open Freetube and play a video
2. middle-click on another thumbnail to open this other video in another window
3. in this newly opened window : save a video (using the star icon)
4. close this window (--> they both close, another bug)
5. reopen Freetube, look at the saved videos : the one you just saved is not in the list
6. open another windows (same as 2) : surprisingly, in saved video, you can see the video you saved at step 3 !

Edit:  it's quite weird actually, it seems that the number of opened windows when you "save" a video as an impact on the window where you'll see the saved video ... 
- have 2 opened window when saving one. Close all windows, you'll find it back it in 2nd opened window
- have 3 opened window when saving one. Close all windows, you'll find it back it in 3rd opened window
-

**Environment Information (please complete the following information):**
Kununtu 21.10
 - FreeTube 15.1 beta
- Appimage
 - Primary API Used: Local API

Thanks !

### PR DESCRIPTION
**Pull request by Svallinn**
**Pull Request Type**
- Feature Implementation

Closes #1919

**Description**
This took me way too long to put together, but here it is, ***full database synchronization across Electron windows***

A lot of changes were necessary for this to not look like an absolute clusterfuck, especially the way the store interacted with the database needed a complete revamp, but I'm not gonna fill this description with details.
I'm the kind of individual who makes 10 paragraph long commit messages where necessary, so read the commit messages to get the details.

All critiques are welcome.

**Testing**
It has been thoroughly tested by me, but obviously, I'd like other people testing it too.

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Coudnt test but this will probably fix https://github.com/FreeTubeApp/FreeTube/issues/1919

**Comment by GLLM** [comment]
> Coudnt test but this will probably fix #1919

I'll test it when this reach the next version ;)

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
Works like a charm!

This indeed closes #1919

**Review by ChunkyProgrammer — APPROVED** [review]
Tested VIA the playlists branch. Works well

**Comment by PikachuEXE** [comment]
I have been using this for week on Mac and Windows and it works flawlessly for me

**Pull request merged**
