### PR TITLE
Reset sort by when changing channels

### LINKED ISSUE #3287: [Bug]: Sort by broken on channel page
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

https://user-images.githubusercontent.com/73130443/224539155-02e4bee4-bd46-481f-9eda-c1d226e72f30.mp4

Didnt test the playlist tab but im pretty sure it is the same there.

### Expected Behavior

Sort by works correctly.

### Issue Labels

feature stopped working

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/903edc2e6eeae46893839607bf952e120cbe2260

### Operating System Version

Win10 22h2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by absidue**
# Reset sort by when changing channels

## Pull Request Type

- [x] Bugfix

## Related issue
closes #3287 

## Description
When you change channels the sort by values currently don't get reset, this pull request fixes it (I've already pushed a fix for the live sort by to the live tab PR). That means that while the drop down shows it correctly sorted by newest, the actual API requests use the value from the previous channel page, which is fixed now.

## Testing 
Set the sort by values on the videos and playlists tabs to something other than newest, change to a different channel, make sure the videos and playlists are sorted by newest.

## Desktop

- **OS:** Windows
- **OS Version:** 10
- **FreeTube version:** 0.18.0

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
https://user-images.githubusercontent.com/73130443/224554728-bb5e771b-290c-45cf-9cb9-5d7075575603.mp4

Is this expected behavior?

**Comment by absidue** [comment]
uhh no that's not supposed to happen 😅

**Comment by absidue** [comment]
Okay so this is an extremely weird bug, for some reason the sort by elements get reset when you switch away from the about tab, I have no idea why but rearranging the elements in the component seems to stop that happening, I don't know if this is an issue on the Vue side or the browser side or if the Channel view is just to expensive for Vue to render and it gives up part way through.

**Comment by PikachuEXE** [comment]
These changes might help
image
image

But since I don't really understand vue value binding so I will leave you to test what's best to fix the issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Okay so this is an extremely weird bug, for some reason the sort by elements get reset when you switch away from the about tab, I have no idea why but rearranging the elements in the component seems to stop that happening, I don't know if this is an issue on the Vue side or the browser side or if the Channel view is just to expensive for Vue to render and it gives up part way through.

Live tab doesnt seem to be affected by this. Only the videos and playlist tab are affected by this weird reset

**Comment by PikachuEXE** [comment]
This should be rebased, I can't see live tab now :S

**Comment by PikachuEXE** [comment]
Found a error with Invidious API
image
image

**Comment by PikachuEXE** [comment]
Seems like a rerender mess
image

**Comment by PikachuEXE** [comment]
Just fixed it (rerender result)
Just need to add `key`
https://vuejs.org/api/built-in-special-attributes.html#key

**Comment by absidue** [comment]
Thanks, looks like the key fixes it (can't approve my own PR, so you'll have to do it).

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — CHANGES_REQUESTED** [review]
Incorrectly labeled as Newest

https://user-images.githubusercontent.com/73130443/226172221-e9b703b8-d1f1-4c25-bda6-8b9823e0b6ac.mp4

Incorrectly labeled as Most Popular

https://user-images.githubusercontent.com/73130443/226172224-ec733a92-4e67-4935-9153-a0296fb53f5e.mp4

**Comment by PikachuEXE** [comment]
Recorded using Local API, Live Stream Hidden

No issue for sort component after coming back from about tab

https://user-images.githubusercontent.com/1018543/226240567-37b10b1b-d0cf-45f7-a39a-4d75386f2799.mov

No issue for sort component after non default selected and switched to another channel

https://user-images.githubusercontent.com/1018543/226240573-0dbd9bee-5042-4bf7-a3a1-a4bae05dd637.mov

Or is it different after build?

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Like Pikachu I can't replicate the behaviour in your video on my end either 🙈.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@absidue ok i checked again and the first video doesnt happen to me anymore but the second one is persistent

**Comment by PikachuEXE** [comment]
Not related to this PR but I got this error after I pull latest changes and testing channel switching
image

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Not related to this PR but I got this error after I pull latest changes and testing channel switching image

The first error in the screen is the same one i get in [my second video](https://github.com/FreeTubeApp/FreeTube/pull/3289#pullrequestreview-1347430780). I think that because of that error i keep seeing Most Popular instead of Newest.

**Comment by absidue** [comment]
Closing as was fixed in #3533 in the mean time.

**Pull request closed without merging**
