### PR TITLE
[Feature] Add Right To Left language support

### LINKED ISSUE #1550: Please add RTL interface
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Hebrew and Arabic (the main RTL languages) are written from right to left. Currently, the interface of FreeTube is from left to right, even for right-to-left languages. Adding it will improve the user experience of speekers of right-to-left languages.

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Add RTL language support
---

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
closes #1550 

**Description**
This pr will display arabic & hebrew text from right to left.

**Screenshots (if appropriate)**
Top Nav:
image

Settings:
image

Video:
image

Comments:
image

Trending:
image

About:
image

Channel (Videos/Playlists)
image

Channel (About)
image

Playlists:
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 
This PR was tested by navigating to pages using an RTL language(Hebrew) and navigating them using an LTR language(English) to make sure there were no regressions

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.2

**Additional context**
I don't understand any RTL languages so if someone who knows one is able to point out any errors that I missed then that'd be appreciated.

Some additional changes still need to be made:
- [ ] fix on/off toggle animation

### CODE REVIEW

**Comment by peepopoggers** [comment]
From your previews, this looks very good so far.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just checking in what is the progress on this?

**Comment by ChunkyProgrammer** [comment]
> Hi @ChunkyProgrammer just checking in what is the progress on this?

Sorry, didn't see your comment. It's mostly done

**Comment by ChunkyProgrammer** [comment]
Not a big fan of the way this was implemented so I will close this PR to see if I can find a better way

**Comment by jasonhenriquez** [comment]
Dumb question: Can't 90% of this be done with just using the `direction: rtl` [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/direction)? @ChunkyProgrammer 

Screenshot_20230827_003018

**Comment by ChunkyProgrammer** [comment]
> Dumb question: Can't 90% of this be done with just using the `direction: rtl` [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/direction)? @ChunkyProgrammer
> 
> Screenshot_20230827_003018 **Caption:** A picture of FreeTube after I just added a `direction: rtl !important` rule in my local env for demoing this point.

Yeah, most of it can be done by that. All cases of margin-left/margin-right and left/right also need to be updated and some icons need to be flipped when using rtl. Setting the dir to rtl should also be done through the html attribute instead of css https://www.w3.org/International/questions/qa-bidi-css-markup

**Comment by jasonhenriquez** [comment]
Ah okay, I see that now. The properties listed in [the last post by cage rattler here](https://stackoverflow.com/questions/36181421/managing-the-css-direction-for-ltr-and-rtl) should be the cleaner option that you were looking for without so much conditional styling. Would you like to implement it still? If not, I wouldn't mind taking it on. @ChunkyProgrammer

**Comment by ChunkyProgrammer** [comment]
@jasonhenriquez feel free to take it on 🙂

**Pull request closed without merging**
