### PR TITLE
[Fix] Freetube does not play the next video in a playlist when using the Invidious API 

### LINKED ISSUE #1487: Freetube does not play the next video in a playlist when using the Invidious API
**Behavior of the program**
Freetube plays the same video twice instead of moving on to the next in a playlist. After playing it the second time it stops altogether. (Nothing happens other than a message: `Playing next video`)
Whether I click next video manually or wait for one to finish + 5 seconds does not matter.

**Expected behavior**
I expect freetube to keep playing the next video in the playlist, whether it be on shuffle play or linear.

**To Reproduce**
Open a playlist. [for example this one](https://www.youtube.com/playlist?list=PLJQswUar8fW97sPan8J4dsIpNJpswqFZ-)
Play any video in it.
Click next, or scrub to just before the end + wait 5 seconds.
The alerts will tell you Freetube is trying to play the next video.
I get `Error: No video id found: undefined` and `{"error":"Video unavailable"}`.
(Click the video that should've been next in line. It'll work fine.)

**Environment Information (please complete the following information):**
 - OS: GNU/Linux 5.12.0-9.2-liquorix-amd64
 - OS Version: Kubuntu 20.04
 - FreeTube version: `freetube_0.13.2_amd64.AppImage`
 - Primary API Used: Invidious API (I tested on Local API, that fixed it)

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
[Fix] Freetube does not play the next video in a playlist when using the Invidious API 
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #1487

**Description**
I updated the playlist code to allow the playlist controls (shuffle, next, back, autoplay next vid) to work with invidious api

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.2

**Additional context**

### CODE REVIEW

**Review by PikachuEXE — COMMENTED** [review]
1. We can have commits squashed (including the merge commit) unless there are reasons to keep some commits separated
2. What is `value_a ?? value_b`? New JS syntax?

**Comment by ChunkyProgrammer** [comment]
> 1. We can have commits squashed (including the merge commit) unless there are reasons to keep some commits separated
> 2. What is `value_a ?? value_b`? New JS syntax?

1. Thanks, I didn't realize you could do that so I will do that.
2. It's similar to `value_a || value_b`. I think this documentation will explain it better than I could: [Nullish Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator ).

**Comment by PikachuEXE** [comment]
Here are the top search results for `git squash commit` in case anyone needs:
- https://www.git-tower.com/learn/git/faq/git-squash/
- https://gitbetter.substack.com/p/how-to-squash-git-commits

Thanks for the Nullish Coalescing Operator article
TIL

**Review by jasonhenriquez — APPROVED** [review]
I experienced this bug consistently on a different build and stopped experiencing it after building with these changes. I can confidently say that this PR fixes the issue.

**Review by PikachuEXE — APPROVED** [review]
I tested this locally

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lint blocks the merge

**Pull request merged**
