### PR TITLE
chore: enable logs for local development

### PR DESCRIPTION
**Pull request by 80avin**
# Title

## Pull Request Type

- [x] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes https://github.com/FreeTubeApp/FreeTube/issues/6296

## Description

I'm not sure if everyone is facing issue with sandboxing, that's why I have added that only as a comment. But enabled the logs so that such errors can be easily identified.

## Screenshots 

image

## Testing 

Only tested using eslint ( as part of commit hook )

## Desktop

- **OS:** Kubuntu
- **OS Version:** 24.04
- **FreeTube version:** https://github.com/FreeTubeApp/FreeTube/commit/0e8db50ed07d0b721104031c1cfc81721cdbbe38

## Additional context

No

### CODE REVIEW

**Comment by absidue** [comment]
You need to set up an apparmor profile for Electron. Disabling the sandbox is not the right solution to the problem, the error is telling that it is failing to start because something wrong in your environment (in your case Ubuntu being way too restrictive) and your solution is to just disable Electron's security.

Additionally Electron's logging is disabled by default in dev as 99.98% of the time it is irrelevant and just spams the console. But in the rare case that you do need it all you need to do is uncomment those lines temporarily.

**Comment by 80avin** [comment]
@absidue I can understand.

Is your opinion the same about printing the exit status? or, inheriting only stderr of electron process ?

**Comment by absidue** [comment]
You will still get unnecessary logs with just stderr.

**Comment by 80avin** [comment]
But exit status will only be printed once per session.
And that is also sufficient to hint the new developers.

If we are disabling logs, I suggest we show the non-zero/non-restart exit status with the message like `Electron exited with code {code} on receiving signal {signal}. Enable electron logging in `_scripts/dev-runner.js` to enable logs`

Or, have an environment variable to enable electron logging as otherwise, unstaged changes would create issues.

**Comment by 80avin** [comment]
> if you are the kind of person to commit every changed file every single time without doing a quick check, then it really is your own fault.

I am fine with the closure of this PR and was only seeking your opinion on showing the electron's exit status as without that, we are completely hiding any sign of crash from the electron process.
I originally came to implement https://github.com/FreeTubeApp/FreeTube/issues/333 as I liked the idea and found it doable. But, I'm not sure where this assumption is coming from or where is the argument going.

If someone is capable of hand-picking each hunk for staging, he should be doing it and not finding any efficient process. He should do 2 extra steps of stash push/pop before every rebase, almost every checkout, etc because he can.


Nevertheless... This was just a bad assumption for you to make. I hope it is just an unfortunate situation or timing for me to bother you and we can have better arguments in future.

**Pull request closed without merging**
