### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by efb4f5ff-1298-471a-8973-3d47447115dc**
# Create stale.yml

## Pull Request Type

- [ ] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [x] Other - Automation

## Description

So this workflow will keep our backlog healthy.

- When an issue is stale for 30 days the author gets notified by a bot message to let us know if the issue is still relevant and a stale label gets added. The author will receive 5 days to respond otherwise the issue will be closed. We can remove the stale label when we know the issue still relevant. Removing the label is the same as receiving an comment from the author.
- When a PR is stale for 45 days the author gets notified by a bot message to update the PR or leave a comment with a update why there is no activity and stale label gets added. The author will receive 10 days to comment or update the PR otherwise the PR will be closed. We can remove the stale label if we know its not stale. Removing the label will be the same as comment/update from the author and result in timer reset.

For PR's this means that author dont go lazy on us by not updating their PR and also the other way around that we dont go lazy on them by not reviewing frequently (but that isnt really a problem from our side atm)

For issues this means we have to evaluate if some issues are really valid. Allot are so u can just remove the label :). Sounds like a chore and probably is because allot of issues will receive stale status but im willing to do most of it and go through the backlog.

On another note we still have the `waiting for author workflow` that is more going to be used for new issues when we need more info on something. We probably need to update the time window from 21days to 14 (or something else).

All time stamps u see in the description are open for change!

I suggest 
- 14 days issue close on `waiting author` workflow
- 28 days for issue stale 
- 7 days before issue close
- 42 days for pr stale
- 14 days for pr close

## Testing 

tested on issue https://github.com/FreeTubeApp/Test-Repo/issues/82
tested on pr created within repo https://github.com/FreeTubeApp/Test-Repo/pull/90
tested on pr created from fork https://github.com/FreeTubeApp/Test-Repo/pull/91

### CODE REVIEW

**Comment by absidue** [comment]
I agree with your suggested numbers.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
👍 waiting for others to chime in before doing senseless commits

**Comment by PikachuEXE** [comment]
42 days for pr stale might be quite long with 14 days for pr close?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm that would give the author 8 weeks to do something before bot to closes the pr

Maybe 28 stale
14 days for pr close?

**Comment by ChunkyProgrammer** [comment]
I'm worried that this might close valid issues that are just inactive

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thats why we can just remove the label and nothing will happen. Also i'll always ask when im not certain about removing a label

**Review by absidue — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]
OK on updated times

**Review by ChunkyProgrammer — APPROVED** [review]

**Pull request merged**
