### PR TITLE
Hiding thumbs-up icon when the hide Comment Likes setting is enabled

### LINKED ISSUE #1906: Enable "Hide Comment Likes" does not hide like button in the comments
**Behavior of the program**
Enable "Hide Comment Likes" does not hide like button in the comments.

**Expected behavior**
Hide like button left on comments when "Hide Comment Likes" is enable.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open FreeTube
2. Click on "Settings"
3. Click on "Distraction Free Settings"
4. Enable "Hide Comment Likes"
5. Open a videos of some kind
6. See Comments

**Screenshots**
screenshot2

### PR DESCRIPTION
**Pull request by varunprasad**
---
Title
---

**Important note**
We may remove your pull request if you do not use this provided PR template correctly.

**Pull Request Type**
Please select what type of pull request this is:
- [X] Bugfix
- [ ] Feature Implementation

**Related issue**
Please link the issue your pull request is referring to. If this pull request fully resolves the relevant issue, put "closes" before the issue number. Example: "closes #123456".

Closes #1906
https://github.com/FreeTubeApp/FreeTube/issues/1906

**Description**
The PR wraps the font thumbs-up icons in the comments section in a v-if that checks if the hideCommentLikes is disabled.

**Screenshots (if appropriate)**

***BEFORE***
1906Before

***AFTER***
1906After

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
I ran it before and after and observed the comments section.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04
 - FreeTube version: v0.15.1 Beta

**Additional context**

### CODE REVIEW

**Review by ChunkyProgrammer — APPROVED** [review]
Lgtm

**Review by peepopoggers — APPROVED** [review]

**Comment by peepopoggers** [comment]
Something to take note, I think the comment expand text may have margin/padding to the left as a spacer between the like icon and itself. However, when the icon is removed, the padding seems to still be there? Maybe I am wrong but if there is padding then I think it should be put on the right of the icon element instead of the comment expand element. Thanks.

**Review by peepopoggers — CHANGES_REQUESTED** [review]
^

**Comment by varunprasad** [comment]
> Something to take note, I think the comment expand text may have margin/padding to the left as a spacer between the like icon and itself. However, when the icon is removed, the padding seems to still be there? Maybe I am wrong but if there is padding then I think it should be put on the right of the icon element instead of the comment expand element. Thanks.

Thank you for the feedback. By spacer do you mean the margin-left of 5px set in the commentMoreReplies CSS class?

Also, I'm not very familiar with the GH approval process, but do you require me to conditionally remove that spacer value and merge those changes before this PR can be closed?

If so, I can conditionally change the margin-left to 0px in the commentMoreReplies css class when the hideCommentLikes is true and the comment.isHearted is false.

Once again, thanks for your feedback and I'm looking forward to your reply.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
LGTM

**Review by PikachuEXE — APPROVED** [review]

**Comment by PikachuEXE** [comment]
@peepopoggers You requested change before so this PR is blocked
Could you review when free? thx

**Pull request merged**
