### PR TITLE
Upgrade electron from 16 > 19

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
Might or might not fix issue in #2113

Closes #2358

**Description**
16.x is not supported anymore
From https://www.electronjs.org/blog/electron-17-0
image

[Breaking change in 17.x](https://www.electronjs.org/blog/electron-17-0#breaking-changes) = 
- [`desktopCapturer.getSources`](https://www.electronjs.org/blog/electron-17-0#desktopcapturergetsources-in-the-renderer)
- The end

[Breaking change in 18.x](https://www.electronjs.org/blog/electron-18-0#breaking-changes) = 
- [Removed `nativeWindowOpen`](https://www.electronjs.org/blog/electron-18-0#removed-nativewindowopen)
- The end

[Breaking change in 19.x](https://www.electronjs.org/blog/electron-19-0#breaking-changes)

**Screenshots (if appropriate)**
N/A

**Testing (for code that is not small enough to be easily understandable)**
Use test build daily in different OS

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 12.1
 - FreeTube version: 5d4048571f9dcb9f57c4f215ae59b00ebe0d20d1

**Additional context**

### CODE REVIEW

**Comment by absidue** [comment]
CI build artifacts here: https://github.com/absidue/FreeTube/actions/runs/2703335841

**Comment by wildwestrom** [comment]
Got a couple errors when running `pacman -U` on the `.pacman` file.
I don't know how to fix it (yet), but I figured I should leave this feedback for now.
```
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating icon theme caches...
(3/4) save-package-list.hook
error: local database is inconsistent: name mismatch on package freetube-0.17.0-nightly
error: local database is inconsistent: version mismatch on package freetube-0.17.0-nightly
(4/4) Updating the desktop file MIME type cache...
```

**Comment by wildwestrom** [comment]
@absidue Could you please run another CI artifact so I can test the latest commit?

**Comment by absidue** [comment]
@wildwestrom The artifacts will be here when the build finishes: <https://github.com/absidue/FreeTube/actions/runs/2756087579> (so they will probably be done by the time you see this).

**Comment by wildwestrom** [comment]
For anyone who hasn't dealt with a .pacman file, it's apparently pretty easy to use.
First `unzip` the tarball. Then run `pacman -U` to install it. Before installing another nightly, you need to manually remove the previous one with `pacman -R`. Also know that pacman will complain about the database being inconsistent, but that goes away after uninstalling.

**Comment by toby63** [comment]
Just used a build ([freetube-git](https://aur.archlinux.org/packages/freetube-git) (with minor modifications to use electron19)) with this patch on Manjaro Linux, all seems to work great.
Electron19 also seems to improve performance and UI loading etc.

I am using Wayland by the way.

**Comment by PikachuEXE** [comment]
Anyone wanna try [electron 20](https://github.com/electron/electron/releases/tag/v20.0.0)? 🤣

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
sure would u like to open up a PR 😬

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
https://github.com/FreeTubeApp/FreeTube/pull/2448

Testing it is another thing...

**Comment by PikachuEXE** [comment]
PIP fix included
Should we remove the WIP label?

**Pull request closed without merging**
