### PR TITLE
Open youtube links in description in Freetube

### LINKED ISSUE #811: YouTube links in e.g. descriptions open in external browser instead of FreeTube
**Behavior of the program**
When clicking a link to a different YT video inside e.g. a description within FreeTube, the clicked link opens in the external browser.

Example video: https://youtu.be/UlJB3t55u_c - see description box.

**Expected behavior**
I'd expect links to other videos clicked from within FreeTube to open in FreeTube.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open https://youtu.be/UlJB3t55u_c in FreeTube
2. Click on the youtube.com link in the description
3. Notice how it opens in the external browser

**Environment Information (please complete the following information):**
 - OS: Mac M1/ARM
 - OS Version: macOS Big Sur 11.0.1
 - FreeTube version: 0.9.2 Beta
 - Primary API Used: Local API

### PR DESCRIPTION
**Pull request by MLJBrackett**
---
Open youtube links in description in Freetube
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
Fixes #811 

**Description**
This pull request allows the user to click on a youtube link and have it open in Freetube

**Testing (for code that is not small enough to be easily understandable)**
Tested manually by clicking youtube links in the description.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - OS Version: 10.15.7
 - FreeTube version:  v0.9.3

**Additional context**
Originally the description actually never got parsed because the if statements was checking if descriptionHtml was null or not, we don't want to check descriptionHtml, we actually want to check this.description afterwards there was a just a little regex issue that I fixed afterwards.

### CODE REVIEW

**Comment by MLJBrackett** [comment]
Hey @GilgusMaximus I think I found the error, the descriptionParse function doesn't actually run, I've tested it by trying to just replace everything with 'testing' but nothing in the description gets changed.

Any ideas on what to do next?

**Comment by MLJBrackett** [comment]
Hey @GilgusMaximus check out my pull request. I'm pretty sure I have fixed it, checkout my additional context for the actual bug.

**Comment by GilgusMaximus** [comment]
@MLJBrackett thanks for the contribution and pinning down the problem. I'll have a look at it later this day, as I am currently quite busy. But without testing anything, in general the code looks reasonable to me

**Comment by MLJBrackett** [comment]
No problem @GilgusMaximus take your time, I'm pretty sure the code works from the testing that I've done.

**Comment by PrestonN** [comment]
I'm going to close this, as there are a couple of issues with this approach.

Appending `freetube://` to the YouTube links will only properly function on non-portable versions of FreeTube, which can also affect third party hosting solutions in some cases. This functionality also forces the link to open up into an installation of FreeTube instead of the dev instance that may be running, which makes testing difficult.

The proper solution would be to call `getVideoIdFromUrl` within [this](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/App.js#L261) function in `App.js`. This can then navigate to a video if found, or allow the link to be opened externally if it can't find anything. More functionality for links such as channel / playlists will be included in the near future.

You're welcome to open a new PR with this change if you'd like. I will review it once again if you do so.

**Pull request closed without merging**
