### PR TITLE
Implemented the ability to return to the regular viewing mode from the PiP window after navigating away from the video

### PR DESCRIPTION
**Pull request by SebTota**
---
Added the ability to return to the regular viewing mode from the PiP window after navigating away from the video
---

**Pull Request Type**
- [x] Feature Implementation

**Related issue**
#966 ?
#624 

**Description**
When using Picture In Picture mode and the user navigates away from the video page:
* Return to the video page if the user clicks on the 'Back to video player' button and the PiP video is not paused
* Close the PiP view if the user clicks the 'Close' button or if they click the 'Back to video player' button and the video is paused

**Testing (for code that is not small enough to be easily understandable)**
1.  Open any video
2. Click to watch the video in Picture in Picture mode
3. Navigate away from the video by either starting another video or going to Settings/Subscriptions/etc. page

Test returning to regular viewing mode from PiP mode
* Perform steps 1-3
* Make sure the PiP video is not paused
* Click 'Back to video player' button 

Test closing PiP mode
* Perform steps 1-3
* Click 'Close' button
OR
* Perform steps 1-3
* Make sure the PiP video is paused
* Click 'Back to video player' button

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: Latest development branch
 
**Additional context**
Due to the inability to properly track 'Close' vs 'Back to video player' button clicks, the Picture in Picture window will treat both the 'Close' and 'Back to video player' buttons as close buttons when the video is paused.

### CODE REVIEW

**Comment by SebTota** [comment]
After thinking more about this feature, it seems like maybe it should not pertain to navigating to another video. Rather it should only have this functionality when navigating to the subscription, settings, or any other non video page. I was using this locally and it seems quite distracting to have the PiP video retain on screen when navigating to another video. 

What's the input on this? Should it stay as is and keep the PiP video up no matter where the navigation is going? Or should it only retain the PiP video mode when navigating to another page that is not a video. 

This would make things a bit more complex since the PiP video should probably close again when a video from the subscription (or any other) page is chosen, but it seems like it might be worth the change.

**Comment by GilgusMaximus** [comment]
Okay, so thanks for approaching this and sorry for taking so long to test this.
But unfortunately there are some problematic errors int the implementation at the moment:

1) We have a dedicated router setup in place in order to refer to new pages which handles everything necessary to redirect to a new page. So this should definitely be used over setting the window variable. You only need the video id, which you have access to Watch.js 

2) When opening a video in pip and I then move to another video page, multiple things can happen:
  - If I click on the pip icon of the new video, then the new video opens in pip and starts playing from the timestamp the previous pip video was playing
  - If I am in pip and open another video and click back to full screen, the pip video closes and the newer video starts playing in normal player at the timestamp of the pip video



In regards to 1), it looks something like this:
```
this.$router.push({
              path: `/watch/${videoId}`,
              query: timestamp ? { timestamp } : {}
            })
```
You can find many examples in the code for that.

In regards to 2), we have to find a consistent solution here.
First the new video should not play at the timestamp of the pip video at all times. I would imagine that there is a problem with the association of the timestamp fix you added and the video player FT is trying to apply it to. So removing the timestamp for pip again would also be a valid solution and could be the original reason that was not done (without any research though)

If one clicks on the 'go back' button in pip, I am open to what happens then. Does it close itself and the newer video is played, or does it go all the way back to the original video? The second solution would obviously be nicer and more consistent, but I can see a lot of struggles trying to keep the videoId across Watch instances. One solution could be to use a store variable for last pip video, but that would require some more changes. If this is not done and instead the currently open video starts playing in the normal player, I am fine with this as well.

**Comment by SebTota** [comment]
@GilgusMaximus You brought up a really great use case I didn't think of: when a PiP window exists and the user tries to open another video in PiP. 

I am struggling to find a way to differentiate between a PiP window being closed by a user clicking the "X" button in the PiP window and a user opening up another video in PiP. Both of these events send a "closepictureinpicture" event but have no way of distinguishing how the event was delivered. I'm open to ideas of how to differentiate between the two if anyone has one. 

Feel free to close this pull request for now and I can reopen it at a later date if I am able to find a way to achieve this.

**Comment by GilgusMaximus** [comment]
is it possible to recognize whether the mouse pointer is over the pip player? 
In that case one could check that to determine the difference.

But yeah, pip has no defined standard, so everyone is doing what they want with it.

**Comment by SebTota** [comment]
Not as far as I can tell. The way the pip "element" is treated is quite weird. It doesn't actually refer to the PiP window itself, but rather to the original video player on the screen. As the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#properties_on_the_document_or_shadowroot_interfaces) states

> The pictureInPictureElement property tells you which Element is currently being displayed in the floating window.

I tried also just using the `mousemove` event and trying to see if it would recognize the PiP window as a parentElement, but that also did not work. The only other idea I had was to try to get the coordinates of the PiP window and compare them to where the mouse is. But this introduces a bunch of issues, a major one being that I wasn't able to find a way to get the coordinates of the PiP window. All these issues stem from the fact that you can't reference the actual PiP window as a regular element.

**Comment by GilgusMaximus** [comment]
Yeah this is really not a good way to implement this. Let alone the complexity of this. 
But yeah, if no other idea is left open for the moment I'd close this pull request.

PiP really seems like not so good to support at the moment

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @SebTota just checking in. What is the progress of this? Is this even going to be reviewed because lack of support?

**Comment by SebTota** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I wasn't able to find any new implementation of using PiP in a way that would reliably let us know all the different events that are coming from the PiP window. I think as @GilgusMaximus said, we should probably close this for now and maybe reopen #966 to keep track of new ideas there.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its very unfortunate that there is lack of support for this functionality. If @GilgusMaximus agrees, we can close the PR and maybe reopen #966.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Not as far as I can tell. The way the pip "element" is treated is quite weird. It doesn't actually refer to the PiP window itself, but rather to the original video player on the screen. As the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#properties_on_the_document_or_shadowroot_interfaces) states
> 
> > The pictureInPictureElement property tells you which Element is currently being displayed in the floating window.
> 
> I tried also just using the `mousemove` event and trying to see if it would recognize the PiP window as a parentElement, but that also did not work. The only other idea I had was to try to get the coordinates of the PiP window and compare them to where the mouse is. But this introduces a bunch of issues, a major one being that I wasn't able to find a way to get the coordinates of the PiP window since it only provides the an x and y size property with no location property. All these issues stem from the fact that you can't reference the actual PiP window as a regular element. 

I saw the updated their documentation. Im not sure what it looked like before but maybe there is something new in there that might help us out.

**Comment by SebTota** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  If [this](https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#properties_on_the_document_or_shadowroot_interfaces) is the documentation you are referring to, I do not see anything new that would help in this case.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes i was referring that link. Well thats too bad. I had so much hope :(

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@SebTota I'll take the liberty to close this PR because Luca will be unavailable for a while https://github.com/FreeTubeApp/FreeTube/pull/1568#issuecomment-932809018

**Pull request closed without merging**
