### PR TITLE
Bump Babel to latest version and update Babel targets

### PR DESCRIPTION
**Pull request by absidue**
---
Bump Babel to latest version and update babel targets
---

**Pull Request Type**

- [x] Feature Implementation

**Description**
This pull request bumps the Babel dependencies and changes the Babel targets to Chrome 96 and Node 16, as that's what Electron 16.2.2 uses. It also removes the dependency on `@babel/proposal-object-rest-spread` as that is included in `@babel/preset-env` in ES2018 which both Node 16 and Chrome 96 support.

**Screenshots (if appropriate)**
versions

**Testing (for code that is not small enough to be easily understandable)**
I tested this pull request by clicking around FreeTube and everything worked the way it did before these changes.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: ae0e06c

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
Please resolve merge conflicts

**Comment by absidue** [comment]
Rebased to fix the conflicts. Don't merge it yet as it looks like the dependencies have received updates since I opened this pull request so it makes sense to update them to the latest versions first.

**Comment by PikachuEXE** [comment]
I think since you target Node 16
We need #1898 as well
Not sure why it's been sitting there for months Q_Q

**Comment by absidue** [comment]
Yes, I am pretty sure that PR is needed too.

**Review by PikachuEXE — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by ChunkyProgrammer — APPROVED** [review]

**Pull request merged**
