### PR TITLE
Disable merge conflict detection on draft PRs

### PR DESCRIPTION
**Pull request by PikachuEXE**
## Pull Request Type

- [ ] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [x] Other

## Description

Keep getting notification about having merge conflicts and resolved on **draft** PRs is unnecessary IMO

## Desktop

- **OS:**
- **OS Version:**
- **FreeTube version:**

### CODE REVIEW

**Comment by jasonhenriquez** [comment]
Seeing discussion on the checks not running if a PR is undrafted. [How about this?](https://github.com/orgs/community/discussions/25722#discussioncomment-3248917)

**Comment by PikachuEXE** [comment]
Updated

**Comment by jasonhenriquez** [comment]
Just realized the problem I linked was for something a bit different, so I don't know if that comment is relevant. I'm not familiar with this enough to know if it might have any weird side effects without testing first, so I'll just let others go on ahead

**Comment by PikachuEXE** [comment]
`synchronize` causes actions to run on PRs when base or current branch updated
`ready_for_review` causes actions to run on PRs when they are converted from draft to open (I am not sure if we even need this but anyway it's rare)

Don't think we need `open` and `reopen`

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
Maybe put the if statement before `runs-on`? 
just like in https://github.com/FreeTubeApp/FreeTube/commit/81c35883789dfc6b8b4f013d5911d0db1b83fd20

**Comment by PikachuEXE** [comment]
I simply follow https://github.com/FreeTubeApp/FreeTube/blob/v0.20.0-beta/.github/workflows/label-pr.yml#L11-L12

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
Workflow skip doesnt work yet, tested in https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/62

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
I replace `push` with `edited` (action type of `pull_request`)
Which is triggered when `The title or body of a pull request was edited, or the base branch of a pull request was changed.`
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#pull_request

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
ugh i havent found anything that simply worked because the nature of the workflow requires `synchronize`

**Comment by PikachuEXE** [comment]
Ya without the push event it won't even notify when non draft PR got merge conflict due to push on target branch...
Giving up

**Pull request closed without merging**
