### PR TITLE
Navigation bar style improvements

### LINKED ISSUE #1412: Comment Hears show over bottom bar in smaller window mode
**Behavior of the program**
When in small window mode (when control bar is on bottom) hearts in comments appear over the bottom bar.
Must be a z-index issue with the heart. I am guessing the z index is high so it shows above the profile icon, but the z index is also higher than the bottom bar too.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Change window size to small.
2. Visit any video with hearted comments.
3. Scroll until they should be under control bar.
4. They appear over the control bar.

**Link to video**
All videos

**Screenshots**
image

**Environment Information:**
 - FreeTube version: [e.g. 0.9.0]

### PR DESCRIPTION
**Pull request by vallode**
---
Navigation bar style improvements
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
None, I can open an issue if it's pertinent to do so but I will if you want an issue for each of these small fixes.

Closes #1412 by fixing z-index on navigation bar

**Description**
This fixes a few pet peeves I've had since I started using the app:

* Clear button and search button for the search input in the top nav are now fixed width and have a padding around the bar itself
* Removes the top and bottom margin on `<hr>` in the sidebar**
* Vertically aligns icons in the side bar when closed
* Adds a bit of padding to the hamburger icon to mimic the youtube layout (I saw in #327 that potentially moving away from the youtube menu layout is in the plans but I am not comfortable enough with the codebase yet to do more major changes to layout + it should be discussed beforehand :) )

**This is subjective, I would suggest entirely removing the color from them (opt instead for a gray and making them full width)

**Screenshots (if appropriate)**

Sidebar before:
image

Sidebar after:
image

Search bar before:
image

Search bar after:
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

I resized the screen a few times to make sure the mobile view is working correctly and it seems to be. A quick visual inspection would be nice!

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian
 - OS Version: [e.g. 22] 10
 - FreeTube version: [e.g. 0.8] 0.15.0

**Additional context**
Apologies for jumping into this without an issue. Thought it would be better to get stuck in so I can learn a bit of how the codebase works. Thanks for the great app, appreciate all the work put into it!

### CODE REVIEW

**Review by ChunkyProgrammer — DISMISSED** [review]
Changes LGTM. Edit: just realized I didn't test the design when in mobile mode (small window).

**Comment by peepopoggers** [comment]
I agree with these changes and it looks nicer. Some things I want changed however:
image
Not aligned in this mode

image
Arrows are too far away

image
Text should be to the left until search box is focused

**Comment by peepopoggers** [comment]
@ChunkyProgrammer Works fine on small screen

**Comment by vallode** [comment]
Thank you for the reviews, I will get around to actioning all of the feedback tomorrow :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im not sure but ill put it here anyway. This PR has been merged https://github.com/FreeTubeApp/FreeTube/pull/1462

Maybe u can test it out and see of any changes u made collide with the changes in that PR.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — DISMISSED** [review]
LGTM! Apologies for taking so long

**Comment by PikachuEXE** [comment]
Does the description include all the visible changes made?
I rely on that to do testing

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Does the description include all the visible changes made? I rely on that to do testing

i was in the progress of writing it down for u and noticed that it is indeed not clear what to test. When i tested this i thought it was clear to me but reading everything back made me very confused. 

i'll revoke my approval and would like an updated description

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @vallode i would really like to test this. Please update the testcase in the PR description so the reviewers can test this properly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This PR has been closed because there has been no response to our request for providing a testcase.

**Comment by PikachuEXE** [comment]
Nice to hear from you again
Yes I think smaller changes are easier to be reviewed and have higher chance to be accepted (less chance for dispute)

**Pull request closed without merging**
