### PR TITLE
Fix consecutive sponsor segments not being skipped.

### LINKED ISSUE #3534: [Bug]: SponsorBlock segment not skipped
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to SponsorBlock settings 
2. Enable SponsorBlock
3. Enable Notify when sponsor segment is skipped
4. Set Skip Option for all segments to Auto Skip
5. Set different colors for all the segments
6. Go to https://youtu.be/qLVgr29NMA0
7. Skip to 17:24
8. See that first segment is skipped but the last one isnt

https://github.com/FreeTubeApp/FreeTube/assets/73130443/c92ec882-b24c-469d-81df-073701d888af

### Expected Behavior

Last segment should also be skipped

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/a4d45b5fa8a8a1726808c9eebe307643f8dde9c9

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by RyanHx**
# Fix consecutive sponsor segments not being skipped

## Pull Request Type

- [x] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes #3534

## Description

Changed the implementation of sponsors auto skip. It instead relies on the `mousedown` event on the player's seekbar to detect manual seeking via user input, meaning sponsor segments can now be safely skipped consecutively. I also added a listener for the keyboard hotkeys used for seeking, to prevent auto skipping when moving into a sponsored segment that way. These event listeners are disposed of alongside the Player dispose event as I didn't want them left in the global scope (`document`).

## Testing 

I performed testing on a video with sponsored segments. I tested seeking on the player via clicking, clicking and dragging, and keyboard hotkeys. Currently there are no ramifications I have found. 

## Desktop

- **OS:** Windows 10 Pro
- **OS Version:** 22H2
- **FreeTube version:** 0.20.0

## Additional context

The `keycode` package used to pick up the keyboard hotkeys already exists within the FreeTube project via `video.js`, I didn't add it myself for the purpose of this bugfix.

### CODE REVIEW

**Comment by absidue** [comment]
> The keycode package used to pick up the keyboard hotkeys already exists within the FreeTube project via video.js, I didn't add it myself for the purpose of this bugfix.

Regardless of whether a dependency already exists in node_modules, if you use it in a project, you should always explicitly declare it in that project's dependencies. If you don't declare it and one day `video.js` stops using the `keycode` package, everything will suddenly break and nobody will know why.

That being said the rest of FreeTube, even in the player, manages completely fine without the `keycode` package, so I would prefer if you didn't add an extra dependency at all and just did it the native way.

**Comment by RyanHx** [comment]
I also have a change pending to swap out the [for loop in `ignoreSponsorBlock`](https://github.com/FreeTubeApp/FreeTube/pull/4886/files#diff-02a41b6ac31886e222921f371aad34b0ff9cf7f41f72d095c9cc760b5e0faf99R829) to a forEach, but am hesitant to push it without testing. Unfortunately the SponsorBlock API is down at the moment so no segments can be retrieved. I've been looking around for an API mirror but no luck.

https://status.sponsor.ajay.app/
https://fosstodon.org/@sponsorblock/112224416738802796

**Comment by PikachuEXE** [comment]
Found a video with consecutive sponsor segments
https://youtu.be/NhPdXaTF67U

**Comment by RyanHx** [comment]
Ah sorry yeah I was testing using this one https://youtu.be/5ghgTIBzuRA - it has an intro -> recap/preview -> sponsor at the start.

**Review by PikachuEXE — APPROVED** [review]

**Review by MarmadileManteater — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @RyanHx Thankyou for addressing this issue. Unfortunately i have to close this PR because there is a Player migration coming up. The part you addressed has/will be refactored in the player migration.

**Comment by RyanHx** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I look forward to the new player, but is it not worth just getting this fix through in the meantime? It's a 1 year old bug that I often run into myself 😭

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I understand and share your frustration as I am the one that opened that bug report but it isnt worth it to fix and then refactor your code again

**Comment by RyanHx** [comment]
I figured if it's already in the works it'd just require a rebase onto this, but fair enough.

**Pull request closed without merging**
