### PR TITLE
Prevent packaging unneeded dependency files

### PR DESCRIPTION
**Pull request by absidue**
---
Prevent packaging unneeded dependency files
---

**Pull Request Type**

- [x] Feature Implementation

**Description**
FreeTube's dependencies ship a lot of files that might be useful during development, these files aren't useful for users of FreeTube. As we don't have any control over the majority of the dependencies, we can exclude the files during the electron build and reduce the package size (`resources/app.asar`: 54.2MB -> ~49.5MB~ 35.2MB). This pull request also fixes the webpack builds no longer properly ignoring dotfiles.

**Testing (for code that is not small enough to be easily understandable)**
I tested this by running `yarn run build` and then checking the files produced by the webpack builds in the `dist/` directory and the files produced by the electron build in the `build/` directory. I also clicked around FreeTube just to make sure that no required files were accidentally blacklisted.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 26e4433c999d2c32d925e2b2dae5d1da4886e6e3

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Does this affect `npm run dev/debug` too?
Anyway I probably just include this change in my custom build and use for a week as a test

**Comment by absidue** [comment]
Managed to reduce the size even further :).

**Comment by absidue** [comment]
Yes, this pull request does affect `npm/yarn run dev/debug`, only the changes to the webpack configuration though. The changes to `_scripts/build.js` only affect production builds triggered with `npm/yarn run build`.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
Everything still works like a charm

**Review by GilgusMaximus — APPROVED** [review]
yup can confirm it working on my machine as well and code changes look good to me

**Review by ChunkyProgrammer — APPROVED** [review]
LGTM

**Pull request merged**
