### PR TITLE
Fix channel page ID handling

### LINKED ISSUE #2420: [Bug]: Custom channel URLs resolve by username which is incorrect
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Enter `https://www.youtube.com/c/RealEngineering` into the search bar and hit <kbd>Enter</kbd>
2. The channel goes to https://www.youtube.com/user/realengineering which is the wrong channel

### Expected Behavior

It should go to the correct channel

### Issue Labels

API issue, inconsistent behavior, usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Linux 5.18.4, NixOS, 22.11 (Raccoon), 22.11.20220619.0d68d7c

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by absidue**
---
Fix channel page ID handling
---

**Pull Request Type**
- [x] Bugfix

**Related issue**
closes #2420
fixes a race condition introduced by #2259

**Description**
This pull request resolves two issues relating to the handling of channel IDs on the channel page.

1. Treat `/channel/`, `/user/` and `/c/` channel URLs differently, as a `/user/` and `/c/` URLs with the same id might point to different channels.
2. Fixes the race condition introduced by #2259, that happens if fetching the info is faster than the video or playlist fetching. The issue is that after the info is fetched it overwrites the `id` property with the actual channel ID, so if you entered this URL `https://www.youtube.com/c/linustechtips`, the `id` property is set to `linustechtips` and when the info request returns it overwrites it with the channel ID `UCXuqSBlHAE6Xw-yeJA0Tunw`, as the videos and playlists functions still expect the `id` to be `linustechtips` they abort.

The fix for this was to introduce an `originalId` property that is only updated when the actual channel changes, which is then used for the abort checks.

**Testing (for code that is not small enough to be easily understandable)**
I tested the following URLs:
- https://www.youtube.com/c/linustechtips
- https://www.youtube.com/c/RealEngineering
- https://www.youtube.com/user/realengineering

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.17.0

### CODE REVIEW

**Review by PikachuEXE — COMMENTED** [review]
Do we have a place to stored these "magic values"?

I certainly won't be able to parse all the constant values for `idType` in the future.
Not to mention I can't parse them now.

**Comment by absidue** [comment]
@PikachuEXE As those "magic values" come from yt-channel-info, if we create an enum it should definitely be in yt-channel-info and then imported into FreeTube.

**Review by PikachuEXE — APPROVED** [review]
Tested locally

All 3 provided URLs returned different channels

**Review by ChunkyProgrammer — APPROVED** [review]
Works well, also tested to make sure subpaths worked (ie c/name/playlsts)

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Pull request merged**
