### PR TITLE
Revert #3417

### PR DESCRIPTION
**Pull request by efb4f5ff-1298-471a-8973-3d47447115dc**
# Revert #3417

## Pull Request Type

- [x] Other - Chore

## Related issue

#3417 

## Description

Reverting #3417 because it was merged in the wrong branch

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]

**Review by absidue — APPROVED** [review]

**Comment by ChunkyProgrammer** [comment]
Do we need to revert this?

**Comment by PikachuEXE** [comment]
`master` shouldn't be changed via PR, PR should always point to `development`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sooo... Not merge this?

**Review by ChunkyProgrammer — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It seems like Preston put some extra protections in place for this branch, closing.

**Pull request closed without merging**
