### PR TITLE
Proportional scaling inside grid

### PR DESCRIPTION
**Pull request by Airidasz**
---
Proportional scaling inside grid (subscriptions, Trending, ect)
---

**Pull Request Type**
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
none

**Description**
Cards inside grid (subscriptions, trending and others using the same system) now scale according to grid size instead of the grid just stretching and the content not filling it up.

**Screenshots (if appropriate)**
before:
bad

after:
good

**Testing**
none

**Desktop**
 - OS: Windows 10
 - OS Version: 17763

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of #1503

#1503 also scales it for phones and this one not.


https://user-images.githubusercontent.com/73130443/125501036-97b5c89a-2b6c-4d21-ad5e-5ef0290e333c.mp4

**Comment by ChunkyProgrammer** [comment]
Just as a note for people that test this PR: I think #1646 needs to be reverted for this PR to work properly when merged.

**Comment by jasonhenriquez** [comment]
Yes, this PR will have to remove that line to work properly.

**Review by jasonhenriquez — APPROVED** [review]
Sorry that we have not attended to your PR in so long @Airidasz, it's been a busy time for everyone. This looks much better than the current behavior, great job!

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by peepopoggers** [comment]
To be honest, I kind of like the current layout responsiveness. We could improve for mobile users (on pinephone or something) by making the thumbnails become larger when the width of FT is small enough, however I am not sure this flexing design really suits FreeTube. Also in the preview it looks a bit skippy when made small.

**Comment by Airidasz** [comment]
> 
> 
> To be honest, I kind of like the current layout responsiveness. We could improve for mobile users (on pinephone or something) by making the thumbnails become larger when the width of FT is small enough, however I am not sure this flexing design really suits FreeTube. Also in the preview it looks a bit skippy when made small.

This change is so small compared to the benefit it gives. 
The PR does not change breakpoints at which the layout changes, it only changes the scaling inside those grids. It is (in essence) a one line change (the one with minmax), other code changes are only there to unbreak the watched icon and some other stuff.

And the skippy thing is most likely because of mobile breakpoints, not really the result of this change.

Hope this helps in convincing you :)

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
