### PR TITLE
Fix: parsing video info of videos with like count disabled

### LINKED ISSUE #1911: No title bar, videometada (likes, views, publish date, buttons to save etc.) on some videos of the same channel
**Behavior of the program**
On some channel (I have found one for now) the "header" above the comments, so the bar with all of the video information (channel name, title, subscribe button, publish date, like, dislikes etc.) is missing.

**Expected behavior**
The "info" bar is visible on every video as you'd find it on any other video

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to this channel for instance https://youtube.com/channel/UCjrj3gdo-KL2S_JN_gdNyPw
2. Click on any of the video he published (except the second one, see the screenshot)
3. Don't find the title bar
4. Be sad because you can't share the youtube video link

**Screenshots**
image
image
image

**Environment Information (please complete the following information):**

- OS: EndeavourOS Linux x86_64
- OS Version: Kernel: 5.15.2-arch1-1
- FreeTube version: v0.15.1 Beta
- Installation Method (If applicable): AUR
- Primary API Used: Invidious

**Additional context**
*Console output with one of the bugged video*

```
﻿
renderer.js:2 No sources available
renderer.js:2 MediaImage src can only be of http/https/data/blob scheme: file:///usr/lib/freetube/app.asar/dist/index.html
renderer.js:2 Getting video info please wait...
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/10df06bb/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/10df06bb/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 TypeError: Cannot read properties of null (reading 'toLocaleString')
    at o.parsedLikeCount (renderer.js:2)
    at hn.get (renderer.js:2)
    at hn.evaluate (renderer.js:2)
    at o.parsedLikeCount (renderer.js:2)
    at o.<anonymous> (renderer.js:2)
    at o.t._render (renderer.js:2)
    at o.i (renderer.js:2)
    at hn.get (renderer.js:2)
    at new hn (renderer.js:2)
    at renderer.js:2
renderer.js:2 
(24) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Pt]
renderer.js:2 3
```

*Console output with one of the **non** bugged video*

```
No sources available
renderer.js:2 MediaImage src can only be of http/https/data/blob scheme: file:///usr/lib/freetube/app.asar/dist/index.html
renderer.js:2 Getting video info please wait...
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/f1ca6900/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/f1ca6900/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
(24) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Pt]
renderer.js:2 1
```

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Fix: parsing video info of videos with like count disabled
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #1911 

**Description**
Please write a clear and concise description of what the pull request does.
It will change the like/dislike count to '0' if likes/ dislikes are disabled

**Screenshots (if appropriate)**
image

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes

**Desktop (please complete the following information):**
 - OS: Windows
 - OS 10
 - FreeTube version:  Latest Nightly

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — DISMISSED** [review]
LGTM!

**Comment by PikachuEXE** [comment]
Should it be `0` or `null` or other values?

**Comment by ChunkyProgrammer** [comment]
> Should it be `0` or `null` or other values?

I chose 0 to make it consistent with the comments because the yt-comment module defaults to 0 when comment likes can't be parsed. https://github.com/FreeTubeApp/yt-comment-scraper/blob/df26d1823b02543b0e9cf7a9c26f1a7075bf406e/src/htmlParser.js#L14

**Review by PikachuEXE — APPROVED** [review]

**Comment by peepopoggers** [comment]
Maybe they could be disabled all together?

**Review by PikachuEXE — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Hiers

**Review by peepopoggers — APPROVED** [review]

**Comment by bachig26** [comment]
> > Should it be `0` or `null` or other values?
> 
> I chose 0 to make it consistent with the comments because the yt-comment module defaults to 0 when comment likes can't be parsed. https://github.com/FreeTubeApp/yt-comment-scraper/blob/df26d1823b02543b0e9cf7a9c26f1a7075bf406e/src/htmlParser.js#L14

it will really be misleading to have the counts to null "0", I think it is good to have the current condition of making the like/dislike invisible if disabled.

**Comment by ChunkyProgrammer** [comment]
> > > Should it be `0` or `null` or other values?
> > 
> > 
> > I chose 0 to make it consistent with the comments because the yt-comment module defaults to 0 when comment likes can't be parsed. https://github.com/FreeTubeApp/yt-comment-scraper/blob/df26d1823b02543b0e9cf7a9c26f1a7075bf406e/src/htmlParser.js#L14
> 
> it will really be misleading to have the counts to null "0", I think it is good to have the current condition of making the like/dislike icon invisible if disabled.
> 
> Also, in case if you're going to implement a function of recommendation of videos based on the user pattern within the FreeTube in the future, this argument will be conflicting with each other (I actually don't about this, but might cause some issue if occurs) possibly due to the Local API modifications in later completely development master "Major" versions.

I forgot to update the screenshot for this PR but likes being disabled on the youtube side should look the same as if you hide likes in FreeTube

**Pull request merged**
