### PR TITLE
[Feature] Playlist: Sort videos by published date

### LINKED ISSUE #6223: [Feature Request]: Ability to reorder videos in playlist by date uploaded.
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Sometimes, there are playlists that I have assorted videos in, that I wish to watch in chronological order. When there's a large amount (50+), ordering these by hand is quite painstaking. The only available ordering methods available as of now are added date, title, author, and video length:
image

### Proposed Solution

I'd like an two options added to the list of ordering methods, "Date Uploaded (ascending)" and "Date Uploaded ( descending)", or atleast "Oldest" and "Newest". to sort videos chronologically.

### Alternatives Considered

No alternatives considered. 

### Issue Labels

improvement to existing feature

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by GLEBR1K**
# Playlist: Sort videos by published date

## Pull Request Type

- [ ] Bugfix
- [x] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes #6223

## Description

Add new video order options in user playlists:
- Earliest published date
- Latest published date

## Testing 

The following scenarios tested:
- List view (Subscriptions/Trending/Most Popular/History/Channel):
  - Add a video using the plus icon
  - Add a video using the quick bookmark
- Video player view:
  - Add a video using the plus icon
  - Add a video using the quick bookmark
- Playlist import/export

Side effects:
- Already playlisted videos (have been stored w/o published date) remain w/o published date. During sorting, such videos treated as the earliest (`published = 0`).
- Importing a playlist exported earlier, add videos w/o published date as well.

## Desktop

- **OS:** Windows
- **OS Version:** 11
- **FreeTube version:** a7f738a5260051dfa545b686676fb80564d6cdd2

## Additional context

N/A

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Upcoming videos timestamps are listed in seconds. Could that be changed to be more readable?

image

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is probably out of scope of this PR but im going to mention it anyway. This was an upcoming video but i fetched it through my subscription page using RSS (see #3356 for more info on that) therefore it saved an incorrect publish date. The video is live now so i tried going to the video in the hope that the publish date would get updated in the playlist but it didnt. 

https://github.com/user-attachments/assets/266b0cb8-a739-4a91-b75a-80e50fe7c68b

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Everything lgtm, i sign off when @absidue does

**Comment by absidue** [comment]
I haven't reviewed this fully but I've noticed that instead of using the existing premiereDate or premiereDate fields, this pull request does its own thing, could you please use one of the existing two properties instead.

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc That is expected we never update data in the playlists after they have been added, you are thinking of the watch history.

**Comment by absidue** [comment]
**Non-blocking**: I just want to point out that if we ever add support for importing the playlists from Google Takeout exports, the method we would be using to get the information would not provide the published dates (wouldn't have been a problem before this pull request as FreeTube didn't save them itself).

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by kommunarr — APPROVED** [review]
Thanks for the great work on this!

**concern/chore:** This PR is correctly staying consistent with how we've done it in 1 or 2 other cases, but the sorting logic for when the datum isn't present for a video is debatable. If you prefer to sort by oldest, the videos missing the necessary field pollute the top presented videos. 

The top alternative in my mind would be to sort the videos with the missing field at the bottom of both sort orders, thus keeping both tops clean. The main problem with that, though, is that it makes the discoverability of those missing-datum videos very poor. This isn't relevant for anything needed to be done in this PR, though, just thinking out loud.

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
