### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [ ] Feature Implementation
- [x] Others

**Description**

Add two different Pull Request type in pull request template: Documentation and Others. Should be useful for pull requests 😄

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — CHANGES_REQUESTED** [review]
I prefer Other

**Comment by PeterDaveHello** [comment]
> I prefer Other

@efb4f5ff-1298-471a-8973-3d47447115dc You mean the documentation should be removed?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No i mean that u should rename Others to Other

**Comment by PeterDaveHello** [comment]
Okay, thanks, it's done.

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by ChunkyProgrammer — APPROVED** [review]
LGTM

**Review by absidue — APPROVED** [review]

**Pull request merged**
