### PR TITLE
Fix channel banner padding

### PR DESCRIPTION
**Pull request by vallode**
---
Fix channel banner padding
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Description**
There was padding around the channel banner, this PR removes it to make it look a bit more seamless.

* Changes banners to use CSS variable for the URL
* Removes the  tag in favour of a background-image solution
* Adds semantic h1 and p tags to the channel name and subscriber count

**Screenshots (if appropriate)**
before:
image

after:
image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - OS Version: [e.g. 22] Debian
 - FreeTube version: [e.g. 0.8] upstream/development

### CODE REVIEW

**Review by absidue — COMMENTED** [review]
The code looks good, however if you make the window really wide the banner gets stretched. One solution would be to have it hover in the center when if it were to get too wide?

**Comment by vallode** [comment]
> 

It most certainly would, just gonna need to get my hands dirty with a bit more refactoring :) I'll get it done.

**Review by absidue — DISMISSED** [review]
Thanks looks much better now

**Review by PikachuEXE — CHANGES_REQUESTED** [review]
I agree the channel view for channel with banner becomes better
But seems worse for channel with no banner 

Before
image

After
image

Edit: Forgot to add example channel
Just use video https://youtu.be/8SVpc1Kc0_0 and navigate to its channel

**Review by absidue — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
LGTM!

**Review by PikachuEXE — APPROVED** [review]
Tested with no banner channel
image

**Pull request merged**
