### PR TITLE
Explicitly set the window icon on Linux

### PR DESCRIPTION
**Pull request by mat8913**
- [x] I have read and agree to the [Contribution Guidelines](https://github.com/FreeTubeApp/FreeTube/blob/master/CONTRIBUTING.md)
- [x] I can maintain / support my code if issues arise.

**Notes and Comments about your pull request**

This is the patch I wrote to fix flathub/io.freetubeapp.FreeTube#7. #257 might be related.

### CODE REVIEW

**Comment by PrestonN** [comment]
It's likely that we may not need to check for the OS, as I believe that the Icon doesn't show up for other systems as well.  Let's remove that if check and everything should be good.

**Comment by mat8913** [comment]
In that case, should I just pass the image directly to the `BrowserWindow` constructor? i.e.
```
win = new BrowserWindow({
    ...,
    icon: path.join(__dirname, '..', 'icons', 'iconColor.png')
});
```

**Comment by PrestonN** [comment]
Sorry for the late response.

If that works out for all cases (and I don't see why it wouldn't) then that will likely be the best option.  Let's move forward with that.

**Comment by mat8913** [comment]
It turns out this doesn't actually fix the Flatpak icon problem. I just thought that it did because I had the Debian package installed during testing which does display the icon correctly.

Does it happen to work on Windows or Mac?

**Comment by PrestonN** [comment]
I'll test later tonight when I have access to a Windows device.  I'll update here when I've been able to test it.

**Comment by diogogomes** [comment]
@mat8913,

I removed all configs, icons, menu entries, etc related with freetube and installed again and it **works**.

**FreeTube 0.6.0 Beta (flatpak)**
**Xubuntu 16.04**

**Comment by PrestonN** [comment]
The change works on Windows.  Unfortunately I do not own a Mac to test on that end, so hopefully this fix will work over there as well.

**Comment by PrestonN** [comment]
I will go ahead and merge this this everything seems to be well.  If I see any issues between now and the release that I'm working on then I will make adjustments as needed.

Thanks for the help!

**Pull request merged**
