### PR TITLE
[Fix] comments fallback to invidious api

### PR DESCRIPTION
**Pull request by Imaskiller**
---
[Fix] comments fallback to invidious api
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
https://github.com/FreeTubeApp/FreeTube/issues/1490
https://github.com/FreeTubeApp/FreeTube/issues/1536

**Description**
Fixing the fallback to the Invidious API for fetching comments. It adds the missing payload data.

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes. 

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 1.3.2

**Additional context**
This only fixes the fallback to the invidious API. I made another pull request for fixing the Local API.
Pull request: https://github.com/FreeTubeApp/yt-comment-scraper/pull/24

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]

**Comment by PikachuEXE** [comment]
I normally just rebase and force push to avoid having many merge commits

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by ChunkyProgrammer — APPROVED** [review]
LGTM

**Review by jasonhenriquez — APPROVED** [review]
Tested & verified. Good catch & good job.

**Comment by PikachuEXE** [comment]
`Error: Bad credentials` again 😞

**Pull request merged**
