### PR TITLE
can you add dark theme to the base bar

### PR DESCRIPTION
**Pull request by senolfndk**
can you add dark theme to the base bar
--- 
okok

Title
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
Please link the issue your pull request is referring to.

**Description**
Please write a clear and concise description of what the pull request does.

**Screenshots (if appropriate)**
Please add before and after screenshots if there is a visible change.

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Desktop (please complete the following information):**
 - OS Version: [e.g. 22]
 - FreeTube version: [e.g. 0.8]

**Additional context**

### CODE REVIEW

**Comment by PrestonN** [comment]
This is not a pull request. Please search for an existing issue and make a comment there. If you cannot find an open issue (I'm very confident there is one) then please create a new issue.

**Comment by senolfndk** [comment]
can you add dark theme to the base bar
111077480-fcf04b80-8501-11eb-92fa-feb2383542a8

**Comment by Svallinn** [comment]
Don't post a comment on the pull request again.
Please actually **read** what Preston wrote.
There's already an open issue for this [here](https://github.com/FreeTubeApp/FreeTube/issues/278)

**Comment by senolfndk** [comment]
ok

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 29 Mart 2021 Pazartesi 20:41
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [FreeTubeApp/FreeTube] can you add dark theme to the base bar (#1112)


Don't post a comment on the pull request again.
Please actually read what Preston wrote.
There's already an open issue for this here<https://github.com/FreeTubeApp/FreeTube/issues/278>

**Pull request closed without merging**
