### PR TITLE
Improve playlist long description display

### LINKED ISSUE #1336: Unable to see "share playlist" dropdown field in playlist page
**Behavior of the program**
When a description of a playlist is too long the dropdown will be pushed out of reach.

**Expected behavior**
The dropdown should not be pushed out of reach because of the description. 

**To Reproduce**
See video.

**Link to video**

https://user-images.githubusercontent.com/73130443/119563478-1ed63c00-bd97-11eb-9829-2ad91311f05c.mp4

**Screenshots**
None.

Environment Information (please complete the following information):

    OS: [Win 10]
    OS Version: [20h2]
    FreeTube version: [v0.13.0-nightly-857 Beta]
    Installation Method (If applicable): [Portable]
    Primary API Used: [Local API]

Additional context
There maybe need to be a scroll bar implemented or something like "show more". see screen.
Capture

### PR DESCRIPTION
**Pull request by PikachuEXE**
**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
closes #1336

**Description**
Update playlist page description box max height to ensure that
long description text would not push components below out of sight.

**Screenshots (if appropriate)**
https://user-images.githubusercontent.com/1018543/119927220-9da3c280-bfab-11eb-85d7-c6cd052f3b3d.mp4

**Testing (for code that is not small enough to be easily understandable)**
Visit
- https://www.youtube.com/playlist?list=PL3-sRm8xAzY-556lOpSGH6wVzyofoGpzU
- https://www.youtube.com/playlist?list=PL3-sRm8xAzY9sDilvaWjCwCI0TkUzYdOG 

Update window size & observe visibility of the components below description text

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: 13.0.0 (latest on `development` actually)

**Additional context**

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
By the way u have to add the word "closes" before the issue number to link the issue. After this PR is merged the issue will close automatically instead of staying open and clutter the backlog.

**Comment by PikachuEXE** [comment]
Linter failed since 9 days ago...

**Comment by ChunkyProgrammer** [comment]
> Linter failed since 9 days ago...

Doing a "fetch upstream" should fix the linter issue

**Comment by GilgusMaximus** [comment]
I somehow cannot spot the problem with the linter. I ran linter fix, but it does not change anything. Therefore I am gonna merge this and check with a new PR whether anything is wrong. 

Thanks for adding this and sorry for taking so long, we currently have lot of things to do outside of FT

**Pull request merged**
